/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author JosueGalRe
 */
public class Bitacoras extends javax.swing.JPanel {
    //Declaración de variable
    int tipo = 0;
    /**
     * Creates new form cliente
     */
    public Bitacoras() {
        initComponents();
        //Rellenar el comboBox
        ThirdLayer.BackEnd.FillComboBox(cbxUsuarios, 
                "SELECT (nombres+' '+apellidos) FROM Usuario WHERE idtipousuario NOT IN (4,5)");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErrorUsuario = new javax.swing.JLabel();
        lblErrorFecha = new javax.swing.JLabel();
        lblErrorAccion = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JFormattedTextField();
        Fecha = new javax.swing.JFormattedTextField();
        infofecha = new javax.swing.JLabel();
        cbxUsuarios = new javax.swing.JComboBox<>();
        usuarioDesc = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JLabel();
        btnAccion = new javax.swing.JLabel();
        btnFecha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        imprimirAccion = new javax.swing.JLabel();
        sombraiAccion = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        fechaDesc = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        imprimirUsuario = new javax.swing.JLabel();
        sombraiUsuario = new javax.swing.JLabel();
        lblporUsuario = new javax.swing.JLabel();
        lblporFecha = new javax.swing.JLabel();
        lblporAccion = new javax.swing.JLabel();
        accionDesc = new javax.swing.JLabel();
        btnCrear = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        imprimirFecha = new javax.swing.JLabel();
        sombraiFecha = new javax.swing.JLabel();
        infofecha1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1825));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblErrorUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblErrorUsuario.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorUsuario.setToolTipText("");
        add(lblErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1690, 490, 30));

        lblErrorFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblErrorFecha.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorFecha.setToolTipText("");
        add(lblErrorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 930, 490, 90));

        lblErrorAccion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblErrorAccion.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorAccion.setToolTipText("");
        add(lblErrorAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1430, 520, 30));

        Fecha1.setBorder(null);
        try {
            Fecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fecha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha1.setToolTipText("");
        Fecha1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fecha1.setOpaque(false);
        add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 833, 310, -1));

        Fecha.setBorder(null);
        try {
            Fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha.setToolTipText("");
        Fecha.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fecha.setOpaque(false);
        add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 833, 310, -1));

        infofecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infofecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infofecha.setText("YYYY/mm/DD");
        add(infofecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 890, -1, -1));

        cbxUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxUsuarios.setBorder(null);
        cbxUsuarios.setOpaque(false);
        add(cbxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1567, 710, 50));

        usuarioDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Elige a un usuario de FitLogic y podrás ver un reporte con todas las acciones que ha hecho, del gestionamiento de datos..png"))); // NOI18N
        add(usuarioDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1550, 460, 250));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Combobox usuarios.png"))); // NOI18N
        add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1560, -1, -1));

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta usuario.png"))); // NOI18N
        add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        btnAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta acción.png"))); // NOI18N
        add(btnAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, -1, -1));

        btnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta fecha.png"))); // NOI18N
        add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Elige un tipo de filtropara las bitácoras.png"))); // NOI18N
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setToolTipText("");
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 2810, 540, 40));

        lblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Calendario.png"))); // NOI18N
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        imprimirAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Botón imprimir-1.png"))); // NOI18N
        imprimirAccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imprimirAccionMousePressed(evt);
            }
        });
        add(imprimirAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 1310, -1, -1));

        sombraiAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/sombra imprimir-1.png"))); // NOI18N
        add(sombraiAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 1270, 280, 140));

        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Usuarios.png"))); // NOI18N
        add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 200, 170));

        lblAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Acción ícono.png"))); // NOI18N
        add(lblAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, -1, -1));

        fechaDesc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fechaDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Elige dos parámetros (fecha inicio, fecha fin) y verás un reporte de todo hecho en ese periodo de tiempo.png"))); // NOI18N
        add(fechaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 820, -1, 260));

        lblFecha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Combobox fecha-1.png"))); // NOI18N
        add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 820, -1, -1));

        lblFecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Combobox fecha-1.png"))); // NOI18N
        add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, -1, -1));

        imprimirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Botón imprimir-1.png"))); // NOI18N
        imprimirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imprimirUsuarioMousePressed(evt);
            }
        });
        add(imprimirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1670, -1, -1));

        sombraiUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/sombra imprimir-1.png"))); // NOI18N
        add(sombraiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1630, 280, 140));

        lblporUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Por usuario.png"))); // NOI18N
        add(lblporUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 1480, -1, -1));

        lblporFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Por fecha.png"))); // NOI18N
        add(lblporFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 740, -1, -1));

        lblporAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Por acción.png"))); // NOI18N
        add(lblporAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1110, -1, -1));

        accionDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Las funciones básicas son crear, leer, editar y eliminar datos, elige una tarjeta con la acción que quieres y aparecerá la bitácora con la información..png"))); // NOI18N
        add(accionDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1190, -1, 260));

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta crear.png"))); // NOI18N
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearMousePressed(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1100, 410, 160));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta editar.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1260, 410, 160));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Tarjeta eliminar.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 1100, 410, 160));

        imprimirFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Botón imprimir-1.png"))); // NOI18N
        imprimirFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imprimirFechaMousePressed(evt);
            }
        });
        add(imprimirFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 940, -1, -1));

        sombraiFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/sombra imprimir-1.png"))); // NOI18N
        add(sombraiFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 900, 280, 140));

        infofecha1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infofecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infofecha1.setText("YYYY/mm/DD");
        add(infofecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 890, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //Imprimir bitácora por usuario
    private void imprimirUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirUsuarioMousePressed
        if (cbxUsuarios.getSelectedIndex() != -1){
            int idusuario = ThirdLayer.BackEnd.getExecuteInt(
                    "SELECT idusuario FROM Usuario WHERE (nombres+' '+apellidos) = ?", 
                    cbxUsuarios.getSelectedItem()
            );
            java.util.Map parameters = new java.util.HashMap();
            parameters.put("idusuario",idusuario);
            Reportes.ImprimirReporte("reportes/ReporteBitacoraUsuario.jrxml", parameters, "Bitácora por Usuario");
        }
    }//GEN-LAST:event_imprimirUsuarioMousePressed
    //Imprimir bitácora entre fechas
    private void imprimirFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirFechaMousePressed
        lblErrorAccion.setText("");
        lblErrorFecha.setText("");
        lblErrorUsuario.setText("");
        String [] fecha = Fecha.getText().split("-", 3);
        String [] fecha1 = Fecha1.getText().split("-", 3);
        
        String SFecha = new StringBuilder().append(fecha[0]).append(fecha[1]).append(fecha[2]).toString().trim();
        String SFecha1 = new StringBuilder().append(fecha1[0]).append(fecha1[1]).append(fecha1[2]).toString().trim();
        if (!SFecha.trim().isEmpty() && !SFecha1.trim().isEmpty()){
            String[] fechan = Fecha.getText().split("-");
            String[] fechan2 = Fecha.getText().split("-");
            Integer[] fechas = new Integer[fechan.length];
            Integer[] fechas2 = new Integer[fechan2.length];

            int i = 0;
            for(String f: fechan){
                fechas[i]=Integer.parseInt(f);
                System.out.println(fechas[i]);
                i++;
            }
            
            int i2 = 0;
            for(String f: fechan2){
                fechas2[i2]=Integer.parseInt(f);
                System.out.println(fechas2[i2]);
                i2++;
            }

            if (
                    (
                        (fechas[0] >= 2019 && fechas[1] <= 12) 
                        &&
                        (
                            (fechas[1] == 1 && fechas[2] <= 31) ||
                            (fechas[1] == 2 && fechas[2] <= 29) ||
                            (fechas[1] == 3 && fechas[2] <= 31) ||
                            (fechas[1] == 4 && fechas[2] <= 30) ||
                            (fechas[1] == 5 && fechas[2] <= 31) ||
                            (fechas[1] == 6 && fechas[2] <= 30) ||
                            (fechas[1] == 7 && fechas[2] <= 31) ||
                            (fechas[1] == 8 && fechas[2] <= 31) ||
                            (fechas[1] == 9 && fechas[2] <= 30) ||
                            (fechas[1] == 10 && fechas[2] <= 31) ||
                            (fechas[1] == 11 && fechas[2] <= 30) ||
                            (fechas[1] == 12 && fechas[2] <= 31)
                        )
                    ) 
                    &&
                    (
                        (fechas2[0] >= 2019 && fechas2[1] <= 12)
                        &&
                        (
                            (fechas2[1] == 1 && fechas2[2] <= 31) ||
                            (fechas2[1] == 2 && fechas2[2] <= 29) ||
                            (fechas2[1] == 3 && fechas2[2] <= 31) ||
                            (fechas2[1] == 4 && fechas2[2] <= 30) ||
                            (fechas2[1] == 5 && fechas2[2] <= 31) ||
                            (fechas2[1] == 6 && fechas2[2] <= 30) ||
                            (fechas2[1] == 7 && fechas2[2] <= 31) ||
                            (fechas2[1] == 8 && fechas2[2] <= 31) ||
                            (fechas2[1] == 9 && fechas2[2] <= 30) ||
                            (fechas2[1] == 10 && fechas2[2] <= 31) ||
                            (fechas2[1] == 11 && fechas2[2] <= 30) ||
                            (fechas2[1] == 12 && fechas2[2] <= 31)
                        )
                    )
                ){
                lblErrorFecha.setText("");
                java.util.Map parameters = new java.util.HashMap();
                parameters.put("fecha1",Fecha.getText());
                System.out.println(Fecha.getText());
                parameters.put("fecha2",Fecha1.getText());
                System.out.println(Fecha1.getText());
                System.out.println(parameters.containsValue(Fecha.getText()));
                System.out.println(parameters.containsValue(Fecha1.getText()));
                Reportes.ImprimirReporte("Reportes/ReporteBitacoraFecha.jrxml", parameters, "Bitácora por Fechas");
            } else lblErrorFecha.setText("<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                                    + " por favor verifique los datos otra vez.</p></html>");
        } else lblErrorFecha.setText("<html><p style=\"style-align:center;\">Los campos están vacíos.</p></html>");
    }//GEN-LAST:event_imprimirFechaMousePressed
    //Eventos
    private void btnCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMousePressed
        tipo = 1;
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCrear.setEnabled(false);
    }//GEN-LAST:event_btnCrearMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        tipo = 2;
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        tipo = 3;
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(true);
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_btnEditarMousePressed
    //Imprimir reporte por tipo de acción
    private void imprimirAccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirAccionMousePressed
        java.util.Map parameters = new java.util.HashMap();
        switch (tipo){
            case 0:
                Reportes.ImprimirReporte("reportes/ReporteBitacoraAccion.jrxml", parameters, "Bitácora por Acciones");
                break;
            case 1:
                parameters.put("accion", "elimin");
                break;
            case 2:
                parameters.put("accion", "modifi");
                break;
            case 3:
                parameters.put("accion", "agreg");
                break;
        }
        if (tipo > 0)
            Reportes.ImprimirReporte("reportes/.jrxml", parameters, "Bitácora por Acción");
    }//GEN-LAST:event_imprimirAccionMousePressed
    //Evento
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        tipo = 0;
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Fecha;
    private javax.swing.JFormattedTextField Fecha1;
    private javax.swing.JLabel accionDesc;
    public static javax.swing.JLabel btnAccion;
    private javax.swing.JLabel btnCrear;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    public static javax.swing.JLabel btnFecha;
    public static javax.swing.JLabel btnUsuario;
    private javax.swing.JComboBox<String> cbxUsuarios;
    private javax.swing.JLabel fechaDesc;
    private javax.swing.JLabel imprimirAccion;
    private javax.swing.JLabel imprimirFecha;
    private javax.swing.JLabel imprimirUsuario;
    private javax.swing.JLabel infofecha;
    private javax.swing.JLabel infofecha1;
    public static javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblErrorAccion;
    private javax.swing.JLabel lblErrorFecha;
    private javax.swing.JLabel lblErrorUsuario;
    public static javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    public static javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblporAccion;
    private javax.swing.JLabel lblporFecha;
    private javax.swing.JLabel lblporUsuario;
    private javax.swing.JLabel sombraiAccion;
    private javax.swing.JLabel sombraiFecha;
    private javax.swing.JLabel sombraiUsuario;
    private javax.swing.JLabel usuarioDesc;
    // End of variables declaration//GEN-END:variables
}
