/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosueGalRe
 */
public class ClasesVer extends javax.swing.JPanel {

    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    
    String query1;
    String query2;
            
    /**
     * Creates new form ClasesSeeClase
     */
    public ClasesVer() {
        initComponents();
        //Consultas
        query1 = "SELECT c.idclase, c.descripcion, (u.nombres+' '+u.apellidos), tp.tipo, s.nombre,"
                + "(SELECT DATEDIFF(MINUTE, c.horainicio, c.horafin)) "
                + "FROM Clase c, Usuario u, TipoEquipamiento tp, Equipamiento e, Salon s "
                + "WHERE C.idcoach = U.idusuario AND c.idequipo = e.idequipo AND "
                + "e.idtipoequipo = tp.idtipoequipamiento AND c.idsalon = s.idsalon";
        query2 = "SELECT c.idclase, c.descripcion, (u.nombres+' '+u.apellidos), tp.tipo, s.nombre,"
                + "(SELECT DATEDIFF(MINUTE, c.horainicio, c.horafin)) "
                + "FROM Clase c, Usuario u, TipoEquipamiento tp, Equipamiento e, Salon s "
                + "WHERE C.idcoach = U.idusuario AND c.idequipo = e.idequipo AND "
                + "e.idtipoequipo = tp.idtipoequipamiento AND c.idsalon = s.idsalon AND "
                + "c.descripcion LIKE ?";
        //Modelo para la tabla
        modelo.addColumn("No.");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Coach");
        modelo.addColumn("Material");
        modelo.addColumn("Salon");
        modelo.addColumn("Duracion (m)");
        Tabla.setModel(modelo);
        //Recargar tabla
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        barrabuscar = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1328));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 65, 730, 40));

        barrabuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases - agregar/Barra de búsqueda.png"))); // NOI18N
        add(barrabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1140, 70));

        btnbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Botón buscar.png"))); // NOI18N
        btnbuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscar1MouseClicked(evt);
            }
        });
        add(btnbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 200, 60));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setToolTipText("");
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 1300, 1050));
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnbuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscar1MouseClicked
        UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
    }//GEN-LAST:event_btnbuscar1MouseClicked
    //Validaciones de texto
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_ENTER)
            UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
        if (txtBuscar.getText().trim().length() <= 1 || txtBuscar.getText().trim().isEmpty())
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel barrabuscar;
    private javax.swing.JLabel btnbuscar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
