/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosueGalRe
 */
public class ClasesEditar extends javax.swing.JPanel {
    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    
    String query1;
    String query2;
    
    int modoeditar = 0;
    
    /**
     * Creates new form ClasesEditar
     */
    public ClasesEditar() {
        initComponents();
        //Consultas para la tabla
        query1 = "SELECT c.idclase, c.descripcion, (u.nombres+' '+u.apellidos), tp.tipo, s.nombre,"
                + "(SELECT DATEDIFF(MINUTE, c.horainicio, c.horafin)) "
                + "FROM Clase c, Usuario u, TipoEquipamiento tp, Equipamiento e, Salon s "
                + "WHERE C.idcoach = U.idusuario AND c.idequipo = e.idequipo AND "
                + "e.idtipoequipo = tp.idtipoequipamiento AND c.idsalon = s.idsalon";
        //Modelo
        modelo.addColumn("No.");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Coach");
        modelo.addColumn("Material");
        modelo.addColumn("Salon");
        modelo.addColumn("Duracion (m)");
        Tabla.setModel(modelo);
        //Rellenar los comboBoxs
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        
        cbxCoachs.removeAllItems();
        cbxEquipo.removeAllItems();
        cbxSalones.removeAllItems();
        
        String equipo = "SELECT tp.tipo "
                + "FROM TipoEquipamiento tp, Equipamiento e WHERE tp.idtipoequipamiento = e.idtipoequipo AND tp.estado = 'A'";
        ThirdLayer.BackEnd.FillComboBox(cbxEquipo, equipo);
        
        String coach = "SELECT (nombres+' '+apellidos) "
                        +"FROM Usuario u, TipoUsuario t WHERE u.idtipousuario = t.idtipousuario AND u.idtipousuario = 4 AND "
                        +"u.idestado = 1";
        ThirdLayer.BackEnd.FillComboBox(cbxCoachs, coach);
        
        String salon = "SELECT nombre FROM Salon WHERE idestadosalon = 1";
        ThirdLayer.BackEnd.FillComboBox(cbxSalones, salon);        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        cbxEquipo = new javax.swing.JComboBox<>();
        cbxSalones = new javax.swing.JComboBox<>();
        cbxCoachs = new javax.swing.JComboBox<>();
        txtFin = new javax.swing.JFormattedTextField();
        txtInicio = new javax.swing.JFormattedTextField();
        fondo = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios/Botón buscar-1.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 270, -1, 60));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 170, -1, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar/Boto¦ün buscar-1.png"))); // NOI18N
        btnEliminar.setEnabled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 340, -1, 60));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar/Boto¦ün actualizar.png"))); // NOI18N
        btnActualizar.setEnabled(false);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 410, 200, 60));

        txtNombres.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.setEnabled(false);
        txtNombres.setOpaque(false);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 65, 430, -1));

        cbxEquipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxEquipo.setBorder(null);
        cbxEquipo.setEnabled(false);
        cbxEquipo.setOpaque(false);
        add(cbxEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 150, 50));

        cbxSalones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxSalones.setBorder(null);
        cbxSalones.setEnabled(false);
        cbxSalones.setOpaque(false);
        add(cbxSalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 150, 50));

        cbxCoachs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxCoachs.setBorder(null);
        cbxCoachs.setEnabled(false);
        cbxCoachs.setOpaque(false);
        add(cbxCoachs, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 470, 50));

        txtFin.setBorder(null);
        try {
            txtFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFin.setEnabled(false);
        txtFin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFin.setOpaque(false);
        add(txtFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, 50));

        txtInicio.setBorder(null);
        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInicio.setEnabled(false);
        txtInicio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtInicio.setOpaque(false);
        add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 170, 90, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar/Campos de datos personales.png"))); // NOI18N
        fondo.setEnabled(false);
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 1220, 180));

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setToolTipText("");
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, 1400, 30));

        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setToolTipText("");
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabla);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 1120, 1050));
    }// </editor-fold>//GEN-END:initComponents
    //Declaración de variables
    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombresKeyTyped
    //Eventos
    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        if (modoeditar == 1)
            ActualizarClases();
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (modoeditar == 1)
            Eliminar();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (modoeditar == 1)
            Regresar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (modoeditar == 0)
            Editar();
    }//GEN-LAST:event_btnEditarMouseClicked
    //Eliminar los campos afectados y recargar la tabla
    private void Regresar(){
        if(modoeditar == 1) {
            LimpiarCampos();
            cambiarEstado(false);
            modoeditar = 0;
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        }
    }
    //Muestra los datos de la fila seleccionada
    private void Editar(){
        if (Tabla.getSelectedRow() != -1){
            modoeditar = 1;
            ThirdLayer.BackEndClases.GetClassInfo((Integer) Tabla.getValueAt(Tabla.getSelectedRow(), 0));
            txtNombres.setText(ThirdLayer.BackEndClases.getDescripcion());
            txtInicio.setText(ThirdLayer.BackEndClases.getHorainicio());
            txtFin.setText(ThirdLayer.BackEndClases.getHorafin());
            cbxCoachs.setSelectedItem(ThirdLayer.BackEndClases.getNombrecoach());
            cbxEquipo.setSelectedItem(ThirdLayer.BackEndClases.getNombreequipo());
            cbxSalones.setSelectedItem(ThirdLayer.BackEndClases.getNombresalon());
            cambiarEstado(true);
        }
    }
    //Eliminar el usuario seleccionado
    private void Eliminar(){
        if (Tabla.getSelectedRow() != -1){
            System.out.println(ThirdLayer.BackEndClases.getIdsalon());
            if (JOptionPane.showConfirmDialog(
                    null, 
                    "¿Desea eliminar la clase?", 
                    "Advertencia", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) 
                    == JOptionPane.YES_OPTION){
                if (ThirdLayer.BackEndClases.EliminarClase()){
                       UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                } else JOptionPane.showMessageDialog(null, "No se ha podido eliminar el usuario.", "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    //Cambiar el estado de los componentes
    private void cambiarEstado(boolean value){
        fondo.setEnabled(value);
        txtNombres.setEnabled(value);
        txtInicio.setEnabled(value);
        txtFin.setEnabled(value);
        cbxCoachs.setEnabled(value);
        cbxEquipo.setEnabled(value);
        cbxSalones.setEnabled(value);
        btnActualizar.setEnabled(value);
        btnEliminar.setEnabled(value);
        btnCancelar.setEnabled(value);
    }
    //Limpiar campos de texto
    private void LimpiarCampos(){
        txtNombres.setText("");
        cbxCoachs.setSelectedIndex(-1);
        cbxEquipo.setSelectedIndex(-1);
        cbxSalones.setSelectedIndex(-1);
        txtFin.setText("");
        txtInicio.setText("");
    }
    //Actualizar las clases
    private void ActualizarClases(){
        String [] inicio = txtInicio.getText().split(":", 2);
        String [] fin = txtFin.getText().split(":", 2);
        
        String SInicio = new StringBuilder().append(inicio[0]).append(inicio[1]).toString().trim();
        String SFin = new StringBuilder().append(fin[0]).append(fin[1]).toString().trim();
        
        if (!txtNombres.getText().trim().isEmpty() && cbxCoachs.getSelectedIndex() != -1 &&
            cbxEquipo.getSelectedIndex() != -1 && !SInicio.trim().isEmpty() &&
            !SFin.trim().isEmpty() && cbxSalones.getSelectedIndex() != -1){            
            Integer[] FInicio = new Integer[inicio.length];
            Integer[] FFin = new Integer[fin.length];
            
            int i = 0;
            int i2 = 0;
            
            for(String f: inicio){
                FInicio[i]=Integer.parseInt(f);
                i++;
            }
            for (String f2: fin) {
                FFin[i2]=Integer.parseInt(f2);
                i2++;
            }   
            System.out.println("Hora 1: "+FInicio[0]+"\nHora 2: "+FFin[0]+"\nResultado 1: "+(FInicio[0] >= FFin[0])+
                    "\nMinutos 1: "+FInicio[1]+"\nMinutos 2: "+FFin[1]+"\nResultado 2: "+(FInicio[1] >= FFin[1]));
            if ((FInicio[0] >= 00 && FInicio[0] <= 23) 
                    &&
                (FFin[0] >= 00 && FFin[0] <= 23) 
                    &&
                (FInicio[1] >= 00 && FInicio[1] <= 59) 
                    &&
                (FFin[1] >= 00 && FFin[1] <= 59)
                    &&
                (FInicio[0] <= FFin[0])
                    &&
                ((FInicio[1] <= FFin[1]) 
                    || 
                (FInicio[1] >= FFin[1])
                )) {
                int idSalon = ThirdLayer.BackEnd.getExecuteInt(
                        "SElECT idsalon FROM Salon WHERE nombre = ?", 
                        cbxSalones.getSelectedItem().toString()
                );
                System.out.println(""+idSalon);
                int idEquipo = ThirdLayer.BackEnd.getExecuteInt(
                        "SELECT idtipoequipamiento FROM TipoEquipamiento WHERE tipo = ?", 
                        cbxEquipo.getSelectedItem().toString()
                );
                System.out.println(""+idEquipo);
                int idCoach = ThirdLayer.BackEnd.getExecuteInt(
                        "SELECT idusuario FROM Usuario WHERE (nombres+' '+apellidos) = ?", 
                        cbxCoachs.getSelectedItem().toString()
                );
                System.out.println(""+idCoach);
                if ((ThirdLayer.BackEndClases.GetExistingClass(txtInicio.getText(),txtFin.getText(),idSalon) == false || 
                    ThirdLayer.BackEndClases.GetExistingClassId(txtInicio.getText(),txtFin.getText(),idSalon) == 
                    ThirdLayer.BackEndClases.getIdclase())) {
                    ThirdLayer.BackEndClases.setIdcoach(idCoach);
                    ThirdLayer.BackEndClases.setHorainicio(txtInicio.getText());
                    ThirdLayer.BackEndClases.setHorafin(txtFin.getText());
                    ThirdLayer.BackEndClases.setDescripcion(txtNombres.getText());
                    ThirdLayer.BackEndClases.setIdequipo(idEquipo);
                    ThirdLayer.BackEndClases.setIdsalon(idSalon);
                    if (ThirdLayer.BackEndClases.ActualizarClase()){
                        ClasesFormularioPrincipal.Move(new ClasesEditar(), 2);
                    } else lblError.setText(
                    "<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                            + " por favor verifique los datos otra vez. Tiempo</p></html>"
                );} else lblError.setText(
                "<html><p style=\"style-align:center;\">Ya existe una clase registrada en el mismo salón y la misma hora, "
                        + "por favor verifíque si los datos ingresados están correctos.</p></html>"
            );} else lblError.setText(
                "<html><p style=\"style-align:center;\">La hora ingresada no es válida.</p></html>"
        );} else lblError.setText(
            "<html><p style=\"style-align:center;\">Por favor rellene todos los campos para continuar.</p></html>"
    );}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JComboBox<String> cbxCoachs;
    private javax.swing.JComboBox<String> cbxEquipo;
    private javax.swing.JComboBox<String> cbxSalones;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JFormattedTextField txtFin;
    private javax.swing.JFormattedTextField txtInicio;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
