/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Josue Lacayo
 */
public class Login extends javax.swing.JPanel {
    //Declaración de la variable
    int ver = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        textoX = new javax.swing.JLabel();
        btniniciar = new javax.swing.JLabel();
        btncerrar = new javax.swing.JLabel();
        sombra = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ingresardatos = new javax.swing.JLabel();
        btnRecu = new javax.swing.JLabel();
        barrablur = new javax.swing.JLabel();
        fondologin = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Group 154.png"))); // NOI18N
        add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 70, 200, 150));

        textoX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Llena con tus datos  para iniciar sesión en la aplicación.png"))); // NOI18N
        add(textoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 330, 320, 50));

        btniniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar sesión btn.png"))); // NOI18N
        btniniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btniniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btniniciarMouseClicked(evt);
            }
        });
        add(btniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 770, 440, 60));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar btn.png"))); // NOI18N
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });
        add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1010, -1, 50));

        sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sombra iniciar sesión.png"))); // NOI18N
        add(sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 730, 590, 150));

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 660, 490, 60));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/ojo-h.png"))); // NOI18N
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 585, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(235, 235, 235));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.setDisabledTextColor(new java.awt.Color(235, 235, 235));
        txtUsuario.setOpaque(false);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 473, 360, 40));

        txtContra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtContra.setToolTipText("");
        txtContra.setBorder(null);
        txtContra.setOpaque(false);
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 583, 330, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Campo contraseña.png"))); // NOI18N
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Items/Campo usuario-1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 460, -1, -1));

        ingresardatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar sesión.png"))); // NOI18N
        add(ingresardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 220, 190, 40));

        btnRecu.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        btnRecu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Olvide mis datos.png"))); // NOI18N
        btnRecu.setText("Recuperar Contraseña");
        btnRecu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRecu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuMouseClicked(evt);
            }
        });
        add(btnRecu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 1040, 750, 40));

        barrablur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barra blur gruesa.png"))); // NOI18N
        add(barrablur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 750, 1080));

        fondologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen fondo login.png"))); // NOI18N
        add(fondologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnRecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuMouseClicked
        FramePrincipal.Move(new RecoverPassword());
    }//GEN-LAST:event_btnRecuMouseClicked

    private void btniniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarMouseClicked
        Login();
    }//GEN-LAST:event_btniniciarMouseClicked

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btncerrarMouseClicked

    private void btnVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseExited
        if (ver == 0){
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h.png")
                )
            );
        } else {
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h (2).png")
                )
            );
        }
    }//GEN-LAST:event_btnVerMouseExited

    private void btnVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseEntered
        if (ver == 0){
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h (2).png")
                )
            );
        } else {
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h.png")
                )
            );
        }
    }//GEN-LAST:event_btnVerMouseEntered

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        if (ver == 0){
            txtContra.setEchoChar('\u0000');
            ver = 1;
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h.png")
                )
            );
        } else {
            txtContra.setEchoChar('\u25cf');
            ver = 0;
            btnVer.setIcon(
                new javax.swing.ImageIcon(
                    getClass().
                    getResource("/Recuperar contraseña/ojo-h (2).png")
                )
            );
        }
    }//GEN-LAST:event_btnVerMouseClicked
    //Validación de texto
    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        char c = evt.getKeyChar();
        if((c == KeyEvent.CTRL_DOWN_MASK || c == KeyEvent.ALT_DOWN_MASK))
            evt.consume();
        if(c == KeyEvent.VK_ENTER)
            Login();
    }//GEN-LAST:event_txtUsuarioKeyReleased
    //Método para iniciar sesión
    private void Login(){
        String password = new String(txtContra.getPassword());
        if (!(txtUsuario.getText().trim().isEmpty() ||
            password.trim().isEmpty())){
            System.out.println("No está vacío.");
            if (ThirdLayer.BackEndUsuario.GetUserInformation(txtUsuario.getText())){
                System.out.println("Información cargada.");
                if (ThirdLayer.BackEndUsuario.getIdtipousuario() == 1 ||
                    ThirdLayer.BackEndUsuario.getIdtipousuario() == 2 ||
                    ThirdLayer.BackEndUsuario.getIdtipousuario() == 3) {                    
                    if (ThirdLayer.BackEndUsuario.getIdestado() == 1){
                        System.out.println("El usuario está activo.");
                        if (ThirdLayer.BackEndUsuario.getPrimerinicio() == 1){
                            System.out.println("El usuario tiene el primer inicio.");
                            if (ThirdLayer.BackEndUsuario.getContrasena().equals("FitL0gic") && password.equals("FitL0gic")) {
                                if (JOptionPane.showOptionDialog(this, "Es tu primer inicio de sesión, "
                                        + "por motivo de seguridad, debes ingresar una contraseña nueva", "Advertencia", 
                                    JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null) 
                                        == JOptionPane.OK_OPTION) {
                                    System.out.println("Cargando NewPassword");
                                    NewPassword.setPrimeravez(true);
                                    FramePrincipal.Move(new NewPassword());
                                }//mensaje de error en el momento de ingresar la contrasenia
                            } else lblError.setText(
                            "<html><p style=\"text-align: center;\">"
                                    + "El usuario o contraseña ingresados no son validos.</p></html>");
                        } else {
                            if (ThirdLayer.Hashing.ValidatePassword(password, ThirdLayer.BackEndUsuario.getContrasena())) {
                                FramePrincipal.Move(new MenuPrincipal());
                            } else lblError.setText(
                        "<html><p style=\"text-align: center;\">El usuario o contraseña ingresados no son validos.</p></html>"); 
                        }
                    } else lblError.setText(
                        "<html><p style=\"text-align: center;\">"
                                + "El usuario no está activo. Por favor contácta con un administrador.</p></html>");
                } else lblError.setText(
                    "<html><p style=\"text-align: center;\">El usuario ingresado no tiene permitido accesar.</p></html>");
            } else lblError.setText(
                    "<html><p style=\"text-align: center;\">El usuario o contraseña ingresados no son validos.</p></html>");
        } else lblError.setText("<html><p style=\"text-align: center;\">Los campos están vacíos.</p></html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel barrablur;
    private javax.swing.JLabel btnRecu;
    private javax.swing.JLabel btnVer;
    private javax.swing.JLabel btncerrar;
    private javax.swing.JLabel btniniciar;
    private javax.swing.JLabel fondologin;
    private javax.swing.JLabel ingresardatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel sombra;
    private javax.swing.JLabel textoX;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
