/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Josue Lacayo
 */

public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        //Se modifica lo visible basado en el nivel del usuario
        String nivel = "";
        String nombre = ThirdLayer.BackEndUsuario.getNombres()+" "+ThirdLayer.BackEndUsuario.getApellidos();
        switch (ThirdLayer.BackEndUsuario.getIdtipousuario()){
            case 1:
                nivel = "Administrador";
                break;
            case 2:
                nivel = "Gerente";
                Bitacoras.setVisible(false);
                SombraB.setVisible(false);
                Membresias.setLocation(880, 50);
                SombraM.setLocation(820, 0);
                Clases.setLocation(1390, 50);
                SombraC.setLocation(1330, 0);
                Editar.setVisible(false);
                Gestionar.setLocation(450, 865);
                Configuracion.setVisible(false);
                SombraConfig.setVisible(false);
                break;
            case 3:
                nivel = "Recepcionista";
                Bitacoras.setVisible(false);
                textReportes.setVisible(false);
                btn_reportes.setVisible(false);
                Editar.setVisible(false);
                btnConfiguracion.setVisible(false);
                Configuracion.setVisible(false);
                Gestionar.setVisible(false);
                Usuarios.setVisible(false);
                minimenu.setBounds(30, 20, 480, 1040);
                minimenu.setIcon(
                        new javax.swing.ImageIcon(getClass().
                                getResource("/Menú recepcionista/Rectángulo administrador.png")
                        )
                );
                nombreUsuario.setLocation(70, 60);
                NivelUsuario.setLocation(70, 140);
                btnCerrarsesion.setLocation(80, 970);
                SombraB.setBounds(1470, 840, 380, 100);
                SombraB.setIcon(
                        new javax.swing.ImageIcon(getClass().
                                getResource("/Menú recepcionista/FitLogicMás para tu gimnasio.png")
                        )
                );
                SombraConfig.setLocation(1750, 750);
                SombraConfig.setIcon(
                        new javax.swing.ImageIcon(getClass().
                                getResource("/Menú recepcionista/logo.png")
                        )
                );
                Visualizar.setBounds(40, 400, 470, 150);
                Visualizar.setIcon(
                        new javax.swing.ImageIcon(getClass().
                                getResource("/Menú recepcionista/Cuadro visualizar.png")
                        )
                );
                Agregar.setBounds(40, 550, 470, 150);
                Agregar.setIcon(
                        new javax.swing.ImageIcon(getClass().
                                getResource("/Menú recepcionista/Cuadro agregar.png")
                        )
                );
                Clases.setLocation(1010, 70);
                SombraC.setLocation(940, 20);
                Otros.setLocation(570, 20);
                Membresias.setLocation(570, 70);
                SombraM.setLocation(510, 20);
                salones.setLocation(579, 910);
                facturacion.setLocation(570, 760);
                indumentaria.setLocation(570, 610);
                jLabel3.setLocation(570, 610);
                break;
        }
        nombreUsuario.setText("<html><p style=\"text-align:left;\">"+nombre+"</p></html>");
        NivelUsuario.setText("<html><p style=\"text-align:left;\">"+nivel+"</p></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUsuario = new javax.swing.JLabel();
        Otros = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        Gestionar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        Visualizar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        facturacion = new javax.swing.JLabel();
        salones = new javax.swing.JLabel();
        indumentaria = new javax.swing.JLabel();
        NivelUsuario = new javax.swing.JLabel();
        btnCerrarsesion = new javax.swing.JLabel();
        Configuracion = new javax.swing.JLabel();
        SombraConfig = new javax.swing.JLabel();
        minimenu = new javax.swing.JLabel();
        btn_reportes = new javax.swing.JLabel();
        textReportes = new javax.swing.JLabel();
        Membresias = new javax.swing.JLabel();
        Clases = new javax.swing.JLabel();
        Bitacoras = new javax.swing.JLabel();
        Usuarios = new javax.swing.JLabel();
        SombraM = new javax.swing.JLabel();
        SombraB = new javax.swing.JLabel();
        SombraC = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setLayout(null);

        nombreUsuario.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setToolTipText("");
        nombreUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setMaximumSize(new java.awt.Dimension(340, 100));
        nombreUsuario.setMinimumSize(new java.awt.Dimension(340, 50));
        nombreUsuario.setPreferredSize(new java.awt.Dimension(233, 100));
        add(nombreUsuario);
        nombreUsuario.setBounds(60, 596, 340, 80);

        Otros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Otros.png"))); // NOI18N
        add(Otros);
        Otros.setBounds(770, 5, 102, 48);

        btnConfiguracion.setBackground(new java.awt.Color(102, 102, 102));
        btnConfiguracion.setForeground(new java.awt.Color(102, 102, 102));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Configuración.png"))); // NOI18N
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseClicked(evt);
            }
        });
        add(btnConfiguracion);
        btnConfiguracion.setBounds(130, 940, 190, 50);

        Gestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Botón editar.png"))); // NOI18N
        Gestionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(Gestionar);
        Gestionar.setBounds(450, 1016, 643, 66);

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Accion editar.png"))); // NOI18N
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
        });
        add(Editar);
        Editar.setBounds(450, 866, 643, 168);

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Acción agregar.png"))); // NOI18N
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        add(Agregar);
        Agregar.setBounds(450, 725, 643, 168);

        Visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Acción visualizar.png"))); // NOI18N
        Visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizarMouseClicked(evt);
            }
        });
        add(Visualizar);
        Visualizar.setBounds(450, 595, 643, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú recepcionista/Barra color vertical.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(1120, 595, 10, 450);

        facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú recepcionista/Cuadro facturación.png"))); // NOI18N
        facturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facturacionMouseClicked(evt);
            }
        });
        add(facturacion);
        facturacion.setBounds(1120, 745, 774, 150);

        salones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú recepcionista/Cuadro indumentaria.png"))); // NOI18N
        salones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salonesMousePressed(evt);
            }
        });
        add(salones);
        salones.setBounds(1130, 895, 765, 150);

        indumentaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú recepcionista/Cuadro indumentaria-1.png"))); // NOI18N
        indumentaria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        indumentaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                indumentariaMousePressed(evt);
            }
        });
        add(indumentaria);
        indumentaria.setBounds(1120, 595, 775, 150);

        NivelUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NivelUsuario.setForeground(new java.awt.Color(153, 153, 153));
        NivelUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(NivelUsuario);
        NivelUsuario.setBounds(60, 680, 250, 40);

        btnCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Cerrar sesión.png"))); // NOI18N
        btnCerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarsesionMouseClicked(evt);
            }
        });
        add(btnCerrarsesion);
        btnCerrarsesion.setBounds(50, 1020, 250, 40);

        Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Rectángulo configuración.png"))); // NOI18N
        Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseClicked(evt);
            }
        });
        add(Configuracion);
        Configuracion.setBounds(120, 940, 200, 50);

        SombraConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Configuración/Sombra configuración.png"))); // NOI18N
        add(SombraConfig);
        SombraConfig.setBounds(80, 910, 274, 119);

        minimenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Rectángulo administrador.png"))); // NOI18N
        add(minimenu);
        minimenu.setBounds(-5, 560, 440, 510);

        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Cuadro reportes.png"))); // NOI18N
        btn_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportesMouseClicked(evt);
            }
        });
        add(btn_reportes);
        btn_reportes.setBounds(30, 50, 710, 500);

        textReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Reportes.png"))); // NOI18N
        add(textReportes);
        textReportes.setBounds(40, 5, 170, 40);

        Membresias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3 Menu¦ü administrador/Cuadro membresi¦üas.png"))); // NOI18N
        Membresias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Membresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MembresiasMouseClicked(evt);
            }
        });
        add(Membresias);
        Membresias.setBounds(780, 50, 340, 500);

        Clases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3 Menu¦ü administrador/Cuadro clases.png"))); // NOI18N
        Clases.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClasesMouseClicked(evt);
            }
        });
        add(Clases);
        Clases.setBounds(1155, 50, 340, 500);

        Bitacoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3 Menu¦ü administrador/Cuadro bita¦ücoras.png"))); // NOI18N
        Bitacoras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bitacoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BitacorasMouseClicked(evt);
            }
        });
        add(Bitacoras);
        Bitacoras.setBounds(1530, 50, 340, 500);

        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Usuarios.png"))); // NOI18N
        add(Usuarios);
        Usuarios.setBounds(460, 550, 162, 48);

        SombraM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Sombra membresías.png"))); // NOI18N
        SombraM.setToolTipText("");
        add(SombraM);
        SombraM.setBounds(720, 0, 457, 617);

        SombraB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Sombre bitacoras.png"))); // NOI18N
        add(SombraB);
        SombraB.setBounds(1460, 0, 460, 620);

        SombraC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Sombra clases.png"))); // NOI18N
        add(SombraC);
        SombraC.setBounds(1090, 0, 462, 622);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Fondo blur.png"))); // NOI18N
        add(Fondo);
        Fondo.setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnCerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarsesionMouseClicked
        FramePrincipal.Move(new SignOut());
    }//GEN-LAST:event_btnCerrarsesionMouseClicked

    private void MembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MembresiasMouseClicked
        FramePrincipal.Move(new OtrosMembresias());
        OtrosMembresias.lblLVisualizar.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Visualizar-H.png")
                )
        );
    }//GEN-LAST:event_MembresiasMouseClicked

    private void btnConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseClicked
        FramePrincipal.Move(new OtrosFramePrincipal());
        OtrosFramePrincipal.Move(new OtrosConfiguracion(), 4);
        OtrosFramePrincipal.clases.setIcon(
                new javax.swing.ImageIcon(getClass().
                    getResource("/Backups/Reportes titulo.png")
                )
            );
    }//GEN-LAST:event_btnConfiguracionMouseClicked

    private void ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseClicked
        FramePrincipal.Move(new ClasesFormularioPrincipal());
        ClasesFormularioPrincipal.Move(new ClasesVer(), 1);
        ClasesFormularioPrincipal.lblLVisualizar.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Visualizar-H.png")
                )
        );
    }//GEN-LAST:event_ClasesMouseClicked

    private void facturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facturacionMouseClicked
        FramePrincipal.Move(new OtrosFramePrincipal());
        OtrosFramePrincipal.Move(new OtrosFacturacion(), 1);
        OtrosFramePrincipal.lblLFacturacion.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Facturación.png")
            )
        );
        OtrosFramePrincipal.clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Facturación-1.png")
            )
        );
    }//GEN-LAST:event_facturacionMouseClicked

    private void VisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizarMouseClicked
        FramePrincipal.Move(new UsuarioFormularioPrincipal());
        UsuarioFormularioPrincipal.Move(new UsuarioSeeUsuario(), 3);
        UsuarioFormularioPrincipal.lblTitulo.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Titulo buscar.png")
                )
        );
        UsuarioFormularioPrincipal.lblLVisualizar.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Visualizar-H.png")
                )
        );
    }//GEN-LAST:event_VisualizarMouseClicked

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        FramePrincipal.Move(new UsuarioFormularioPrincipal());
         switch (ThirdLayer.BackEndUsuario.getIdtipousuario()){
            case 1:
                UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
                break;
            default:
                UsuarioFormularioPrincipal.Move(new UsuarioAddCliente(), 1);
                UsuarioAddCliente.setNivel(5);
                break;
         }
        UsuarioFormularioPrincipal.lblTitulo.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Titulo agregar.png")
                )
        );
        UsuarioFormularioPrincipal.lblLAgregar.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Agregar-H.png")
                )
        );
    }//GEN-LAST:event_AgregarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        FramePrincipal.Move(new UsuarioFormularioPrincipal());
        UsuarioFormularioPrincipal.Move(new UsuarioEditUsuario(), 2);
        UsuarioFormularioPrincipal.lblTitulo.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/UsuarioAssets/Titulo Editar.png")
                )
        );
        UsuarioFormularioPrincipal.lblLEditar.setIcon(
                new javax.swing.ImageIcon(getClass().
                getResource("/UsuarioAssets/Editar-H.png")
                )
        );
    }//GEN-LAST:event_EditarMouseClicked

    private void indumentariaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indumentariaMousePressed
        FramePrincipal.Move(new OtrosFramePrincipal());
        OtrosFramePrincipal.Move(new OtrosIndumentaria(), 1);
        OtrosFramePrincipal.lblLIndumentaria.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/Indumentaria/Indumentaria-1.png")
                )
        );
        OtrosFramePrincipal.clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Indumentaria.png")
            )
        );
    }//GEN-LAST:event_indumentariaMousePressed

    private void BitacorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BitacorasMouseClicked
        FramePrincipal.Move(new BitacorasFormularioPrincipal());
        BitacorasFormularioPrincipal.Move(new Bitacoras());
    }//GEN-LAST:event_BitacorasMouseClicked

    private void btn_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportesMouseClicked
        FramePrincipal.Move(new ReportesFormularioPrincipal());
        ReportesFormularioPrincipal.Move(new Reportes());     
    }//GEN-LAST:event_btn_reportesMouseClicked

    private void salonesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salonesMousePressed
        FramePrincipal.Move(new OtrosFramePrincipal());
        OtrosFramePrincipal.Move(new OtrosSalones(), 1);
        OtrosFramePrincipal.lblLSalones.setIcon(
                new javax.swing.ImageIcon(getClass().
                        getResource("/Salones/Salones.png")
                )
        );
        OtrosFramePrincipal.clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Salones/Salones-1.png")
            )
        );
    }//GEN-LAST:event_salonesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Bitacoras;
    private javax.swing.JLabel Clases;
    private javax.swing.JLabel Configuracion;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Gestionar;
    private javax.swing.JLabel Membresias;
    private javax.swing.JLabel NivelUsuario;
    private javax.swing.JLabel Otros;
    private javax.swing.JLabel SombraB;
    private javax.swing.JLabel SombraC;
    private javax.swing.JLabel SombraConfig;
    private javax.swing.JLabel SombraM;
    private javax.swing.JLabel Usuarios;
    private javax.swing.JLabel Visualizar;
    private javax.swing.JLabel btnCerrarsesion;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btn_reportes;
    private javax.swing.JLabel facturacion;
    private javax.swing.JLabel indumentaria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel minimenu;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel salones;
    private javax.swing.JLabel textReportes;
    // End of variables declaration//GEN-END:variables
}
