/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author JosueGalRe
 */
public class NewPassword extends javax.swing.JPanel {
    //Declaración de variables
    int ver = 0;
    boolean valido = false;
    String pass;
    private static boolean primeravez;
    /**
     * Creates new form NewPassword
     */
    public NewPassword() {
        initComponents();
        if (primeravez = true){
            NewPassword.recupass.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/Recupera tu cuentade FitLogic.png")
                    )
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        recupass = new javax.swing.JLabel();
        seguridadimportante = new javax.swing.JLabel();
        barraLateral = new javax.swing.JLabel();
        contrasegura = new javax.swing.JLabel();
        txtRepe = new javax.swing.JPasswordField();
        txtContra = new javax.swing.JPasswordField();
        lblRepeContra = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        lblContrasNoCoiniciden = new javax.swing.JLabel();
        btnCambiar2 = new javax.swing.JLabel();
        btnCambiar1 = new javax.swing.JLabel();
        sombracambiar = new javax.swing.JLabel();
        tecladoBlur = new javax.swing.JLabel();
        dibujo = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setBackground(new java.awt.Color(29, 29, 29));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recupass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Recuperar contraseña.png"))); // NOI18N
        recupass.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(recupass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        seguridadimportante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Tu privacidad es muy importante. Nunca deberías de compartir tus contraseñas de cualquier sitio, estas protegen tu datos personales y podrían caer en manos equivocadas, FitLogic encripta tus contraseñas para que nadie (ni nosotros) sepa cuál.png"))); // NOI18N
        add(seguridadimportante, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, -1, -1));

        barraLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Barra color vertical.png"))); // NOI18N
        barraLateral.setToolTipText("");
        add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        contrasegura.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        contrasegura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Una contraseña segura consta de carácteres variados, usa letras en mayúsculas y minúsculas y números, una buena longitud es de 16 caracteres en adelante..png"))); // NOI18N
        contrasegura.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(contrasegura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 470, 100));

        txtRepe.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtRepe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRepe.setToolTipText("");
        txtRepe.setAutoscrolls(false);
        txtRepe.setBorder(null);
        txtRepe.setOpaque(false);
        txtRepe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraKeyReleased(evt);
            }
        });
        add(txtRepe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 403, 330, 60));

        txtContra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtContra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContra.setToolTipText("");
        txtContra.setAutoscrolls(false);
        txtContra.setBorder(null);
        txtContra.setOpaque(false);
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraKeyReleased(evt);
            }
        });
        add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 273, 330, 60));

        lblRepeContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Campo contraseña.png"))); // NOI18N
        add(lblRepeContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/ojo.png"))); // NOI18N
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 285, -1, -1));

        lblContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Campo contraseña.png"))); // NOI18N
        add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        lblErrorMessage.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMessage.setToolTipText("");
        add(lblErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 470, 50));

        lblContrasNoCoiniciden.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblContrasNoCoiniciden.setForeground(new java.awt.Color(255, 0, 0));
        lblContrasNoCoiniciden.setToolTipText("");
        add(lblContrasNoCoiniciden, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 330, 30));

        btnCambiar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Cambiar contraseña.png"))); // NOI18N
        btnCambiar2.setEnabled(false);
        btnCambiar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiar1MouseClicked(evt);
            }
        });
        add(btnCambiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, -1, -1));

        btnCambiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/btn recuperar contraseña.png"))); // NOI18N
        btnCambiar1.setEnabled(false);
        btnCambiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiar1MouseClicked(evt);
            }
        });
        add(btnCambiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, -1));

        sombracambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/sombra recuperar contraseña.png"))); // NOI18N
        sombracambiar.setEnabled(false);
        add(sombracambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, -1, -1));

        tecladoBlur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Capa negra blur.png"))); // NOI18N
        add(tecladoBlur, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dibujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/ilustración.png"))); // NOI18N
        add(dibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //Botón para cambiar la contraseña
    private void btnCambiar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiar1MouseClicked
        if (btnCambiar1.isEnabled()){
            System.out.println("Está habilitado.");
            String hashedpass = ThirdLayer.Hashing.HashPassword(pass);
            if (ThirdLayer.BackEndUsuario.ChangePassword(hashedpass)){
                System.out.println(ThirdLayer.Hashing.HashPassword(hashedpass));
                if (JOptionPane.showConfirmDialog(this, "La contraseña ha sido cambiada exitosamente", "Acción realizada", 
                    JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
                    if (isPrimeravez() == false){
                        ThirdLayer.BackEndRecuperarContra.EliminarRecuperarContrasena(ThirdLayer.BackEndUsuario.getIdusuario());
                    }
                    if (isPrimeravez() == true){
                        ThirdLayer.BackEndUsuario.ChangeFirstTime();
                    }
                    FramePrincipal.Move(new Login());
                }
            } else System.out.println("La encriptación falló."); 
        }
    }//GEN-LAST:event_btnCambiar1MouseClicked
    //Eventos
    private void btnVerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseEntered
        if (ver == 0){
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo-h.png")
                    )
            );
        } else {
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo.png")
                    )
            );
        }
    }//GEN-LAST:event_btnVerMouseEntered

    private void btnVerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseExited
        if (ver == 0){
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo.png")
                    )
            );
        } else {
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo-h.png")
                    )
            );
        }
    }//GEN-LAST:event_btnVerMouseExited

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        if (ver == 0){
            txtContra.setEchoChar('\u0000');
            txtRepe.setEchoChar('\u0000');
            ver = 1;
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo-h.png")
                    )
            );
        } else {
            txtContra.setEchoChar('\u25cf');
            txtRepe.setEchoChar('\u25cf');
            ver = 0;
            btnVer.setIcon(
                    new javax.swing.ImageIcon(
                            getClass().
                                    getResource("/Recuperar contraseña/ojo.png")
                    )
            );
        }
    }//GEN-LAST:event_btnVerMouseClicked
    //Validaciones de texto
    private void txtContraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyReleased
        String password = new String(txtContra.getPassword());
        String password2 = new String(txtRepe.getPassword());
        System.out.println(password);
        if (!password.trim().isEmpty()){
            Object[] validations = ThirdLayer.Validations.claveEsValida(password);
            boolean result = (Boolean) validations[0];
            String ErrorMessage = (String) validations[1];
            if (result){
                lblErrorMessage.setText("<html><p style=\"text-align:center;\">"+ErrorMessage+"</p></html>");
                if (password2.equals(password)){
                    lblContrasNoCoiniciden.setText("");
                    btnCambiar1.setEnabled(true);
                    btnCambiar2.setEnabled(true);
                    sombracambiar.setEnabled(true);
                    pass = password;
                } else{
                    lblContrasNoCoiniciden.setText(
                            "<html><p style=\"text-align:center;\">Las contraseñas no coinciden.</p></html>"
                    );
                    btnCambiar1.setEnabled(false);
                    btnCambiar2.setEnabled(false);
                    sombracambiar.setEnabled(false);
                }
            } else {
                lblErrorMessage.setText("<html><p style=\"text-align:center;\">"+ErrorMessage+"</p></html>");
            }
        } else lblErrorMessage.setText("<html><p style=\"text-align:center;\">El campo está vacio.</p></html>");
    }//GEN-LAST:event_txtContraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraLateral;
    private javax.swing.JLabel btnCambiar1;
    private javax.swing.JLabel btnCambiar2;
    private javax.swing.JLabel btnVer;
    private javax.swing.JLabel contrasegura;
    private javax.swing.JLabel dibujo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContrasNoCoiniciden;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblRepeContra;
    public static javax.swing.JLabel recupass;
    private javax.swing.JLabel seguridadimportante;
    private javax.swing.JLabel sombracambiar;
    private javax.swing.JLabel tecladoBlur;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtRepe;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the primeravez
     */
    public static boolean isPrimeravez() {
        return primeravez;
    }

    /**
     * @param aPrimeravez the primeravez to set
     */
    public static void setPrimeravez(boolean aPrimeravez) {
        primeravez = aPrimeravez;
    }
}
