/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davidmorataya
 */
public class OtrosSalones extends javax.swing.JPanel {
    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    
    String query1;
    String query2;
    
    int modoeditar = 0;

    /**
     * Creates new form Indumentaria
     */
    public OtrosSalones() {
        initComponents();
        
        query1 = "SELECT s.idsalon, s.nombre, s.descripcion, s.capacidad, es.estado FROM Salon s, EstadoSalon es "
                + "WHERE s.idestadosalon = es.idestadosalon";
        //Modelo
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Capacidad");
        modelo.addColumn("Estado");
        Tabla.setModel(modelo);
        //Rellenar los comboBoxes
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        
        cbxEstado.removeAllItems();
        EditEstado.removeAllItems();
        
        query2 = "SELECT estado from EstadoSalon";
        ThirdLayer.BackEnd.FillComboBox(cbxEstado, query2);
        ThirdLayer.BackEnd.FillComboBox(EditEstado, query2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        EditEstado = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        EditDescripcion = new javax.swing.JTextField();
        EditNombre = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        EditCapacidad1 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sombra = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        sombraAceptar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnCancelar = new javax.swing.JLabel();
        editBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1715));
        setLayout(null);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón agregar.png"))); // NOI18N
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        add(btnAgregar);
        btnAgregar.setBounds(770, 260, 207, 57);

        lblError1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError1.setForeground(new java.awt.Color(255, 0, 51));
        lblError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError1.setToolTipText("");
        add(lblError1);
        lblError1.setBounds(950, 780, 360, 90);

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setToolTipText("");
        add(lblError);
        lblError.setBounds(420, 1560, 570, 40);

        EditEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditEstado.setBorder(null);
        EditEstado.setEnabled(false);
        EditEstado.setOpaque(false);
        add(EditEstado);
        EditEstado.setBounds(830, 1270, 170, 40);

        txtDescripcion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtDescripcion.setBorder(null);
        txtDescripcion.setOpaque(false);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        add(txtDescripcion);
        txtDescripcion.setBounds(280, 320, 370, 42);

        EditDescripcion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditDescripcion.setBorder(null);
        EditDescripcion.setEnabled(false);
        EditDescripcion.setOpaque(false);
        EditDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditDescripcionKeyTyped(evt);
            }
        });
        add(EditDescripcion);
        EditDescripcion.setBounds(252, 1468, 380, 42);

        EditNombre.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditNombre.setBorder(null);
        EditNombre.setEnabled(false);
        EditNombre.setOpaque(false);
        EditNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditNombreKeyTyped(evt);
            }
        });
        add(EditNombre);
        EditNombre.setBounds(210, 1270, 410, 42);

        txtCapacidad.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtCapacidad.setBorder(null);
        txtCapacidad.setOpaque(false);
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });
        add(txtCapacidad);
        txtCapacidad.setBounds(270, 220, 380, 42);

        cbxEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxEstado.setBorder(null);
        cbxEstado.setOpaque(false);
        add(cbxEstado);
        cbxEstado.setBounds(840, 120, 190, 40);

        EditCapacidad1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditCapacidad1.setBorder(null);
        EditCapacidad1.setEnabled(false);
        EditCapacidad1.setOpaque(false);
        EditCapacidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditCapacidad1KeyTyped(evt);
            }
        });
        add(EditCapacidad1);
        EditCapacidad1.setBounds(250, 1370, 380, 42);

        txtNombre.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre);
        txtNombre.setBounds(230, 120, 420, 42);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Visualizar.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(80, 440, 178, 48);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salones/Campos de datos.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(80, 100, 962, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Agregar.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(80, 30, 148, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Editar.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(70, 1160, 108, 48);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salones/Definición editar.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(1060, 1260, 380, 227);

        sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra agregar.png"))); // NOI18N
        add(sombra);
        sombra.setBounds(740, 230, 265, 115);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón aceptar.png"))); // NOI18N
        btnAceptar.setEnabled(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        add(btnAceptar);
        btnAceptar.setBounds(760, 1370, 207, 57);

        sombraAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra aceptar.png"))); // NOI18N
        sombraAceptar.setEnabled(false);
        add(sombraAceptar);
        sombraAceptar.setBounds(730, 1340, 265, 115);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salones/Definición visualizar.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(970, 510, 411, 130);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón editar.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        add(btnEditar);
        btnEditar.setBounds(980, 920, 200, 57);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón eliminar.png"))); // NOI18N
        btnEliminar.setEnabled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(980, 1010, 200, 57);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Sombra eliminar.png"))); // NOI18N
        jLabel14.setEnabled(false);
        add(jLabel14);
        jLabel14.setBounds(960, 990, 248, 105);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra editar.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(900, 850, 356, 213);

        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setToolTipText("");
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabla);

        add(jScrollPane2);
        jScrollPane2.setBounds(80, 520, 790, 590);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar);
        btnCancelar.setBounds(700, 1470, 124, 34);

        editBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salones/Campos de datos.png"))); // NOI18N
        add(editBack);
        editBack.setBounds(60, 1260, 962, 260);
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        if (modoeditar == 1)
            Actualizar();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (modoeditar == 1)
            Regresar();
    }//GEN-LAST:event_btnCancelarMouseClicked
    //Validaciones de texto
    private void EditDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditDescripcionKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditDescripcionKeyTyped

    private void EditNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditNombreKeyTyped
    //Conseguir la información de la fila seleccionada de la tabla
    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (Tabla.getSelectedRow() != -1){
            lblError1.setText("");
            ThirdLayer.BackEndSalon.GetSalonInformation((Integer) Tabla.getValueAt(Tabla.getSelectedRow(), 0));
            EditNombre.setText(ThirdLayer.BackEndSalon.getNombre());
            EditDescripcion.setText(ThirdLayer.BackEndSalon.getDescripcion());
            EditCapacidad1.setText(String.valueOf(ThirdLayer.BackEndSalon.getCapacidad()));
            EditDescripcion.setText(ThirdLayer.BackEndSalon.getDescripcion());
            EditEstado.setSelectedItem(ThirdLayer.BackEndSalon.getSalon());
            modoeditar = 1;
            cambiarEstado(true);
            OtrosFramePrincipal.AddUserMover1();
        } else lblError1.setText(
            "<html><p style=\"text-align:center\">Debes seleccionar un usuario para editarlo.</p></html>");
    }//GEN-LAST:event_btnEditarMouseClicked
    //Eventos
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (modoeditar == 1)
            Eliminar();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        Agregar();
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtCapacidadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void EditCapacidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditCapacidad1KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditCapacidad1KeyTyped

    private void Regresar(){
        if(modoeditar == 1) {
            OtrosFramePrincipal.SeeUserMove1();
            LimpiarCampos("edit");
            cambiarEstado(false);
            modoeditar = 0;
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        }
    }
    //Limpiar campos
    private void LimpiarCampos(String tipo){
        if ("edit".equals(tipo)) {
            EditNombre.setText("");
            EditDescripcion.setText("");
            EditCapacidad1.setText("");
            EditEstado.setSelectedIndex(-1);
        } else if ("add".equals(tipo)){
            txtNombre.setText("");
            txtDescripcion.setText("");
            txtCapacidad.setText("");
            cbxEstado.setSelectedIndex(-1);
        }
    }
    //Cambiar esstado de los componentes
    private void cambiarEstado(boolean value){
        btnEliminar.setEnabled(value);
        editBack.setEnabled(value);
        EditNombre.setEnabled(value);
        EditDescripcion.setEnabled(value);
        EditEstado.setEnabled(value);
        EditCapacidad1.setEnabled(value);
        btnCancelar.setEnabled(value);
        sombraAceptar.setEnabled(value);
        btnAceptar.setEnabled(value);
    }
    //Eliminar salones
    private void Eliminar(){
        if (Tabla.getSelectedRow() != -1 && modoeditar == 1){
            System.out.println(ThirdLayer.BackEndClases.getIdsalon());
            if (JOptionPane.showConfirmDialog(
                    null, 
                    "¿Desea eliminar la clase?", 
                    "Advertencia", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) 
                    == JOptionPane.YES_OPTION){
                if (ThirdLayer.BackEndSalon.EliminarSalon()){
                       UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                } else JOptionPane.showMessageDialog(null, "No se ha podido eliminar el salon.", "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    //Actualizar salones
    private void Actualizar(){
        if (!EditNombre.getText().trim().isEmpty() && !EditDescripcion.getText().trim().isEmpty() &&
            EditEstado.getSelectedIndex() != -1 && !EditCapacidad1.getText().trim().isEmpty()){
            if(ThirdLayer.BackEndSalon.GetExistingClase(EditNombre.getText()) == false || 
                    ThirdLayer.BackEndSalon.GetExistingClaseId(EditNombre.getText()) == ThirdLayer.BackEndSalon.getIdsalon()){
                ThirdLayer.BackEndSalon.setCapacidad(Integer.valueOf(EditCapacidad1.getText()));
                ThirdLayer.BackEndSalon.setDescripcion(EditDescripcion.getText());
                ThirdLayer.BackEndSalon.setNombre(EditNombre.getText());
                int estado = ThirdLayer.BackEnd.getExecuteInt(
                        "SELECT idestadosalon FROM EstadoSalon WHERE estado = ?", EditEstado.getSelectedItem());
                System.out.println(estado);
                ThirdLayer.BackEndSalon.setIdestadosalon(estado);
                if (ThirdLayer.BackEndSalon.ActualizarSalon()){
                    Regresar();
                } else lblError.setText(
                    "<html><p style=\"text-align:center\">Hubo un error al actualizar el salón. "
                            + "Por favor inténtelo de nuevo.</p></html>");
            } else lblError.setText(
                "<html><p style=\"text-align:center\">Ya existe un salón con ese nombre.</p></html>");
        } else lblError.setText(
            "<html><p style=\"text-align:center\">Uno de los campos ingresados está vacío.</p></html>");
    }
    //Agregar salones
    private void Agregar(){
        if (!txtCapacidad.getText().trim().isEmpty() && !txtNombre.getText().trim().isEmpty() &&
            cbxEstado.getSelectedIndex() != -1 && !txtDescripcion.getText().trim().isEmpty()){
            if(ThirdLayer.BackEndSalon.GetExistingClase(txtNombre.getText()) == false){
                ThirdLayer.BackEndSalon.setCapacidad(Integer.valueOf(txtCapacidad.getText()));
                ThirdLayer.BackEndSalon.setDescripcion(txtDescripcion.getText());
                ThirdLayer.BackEndSalon.setNombre(txtNombre.getText());
                int estado = ThirdLayer.BackEnd.getExecuteInt(
                        "SELECT idestadosalon FROM EstadoSalon WHERE estado = ?", cbxEstado.getSelectedItem());
                ThirdLayer.BackEndSalon.setIdestadosalon(estado);
                if (ThirdLayer.BackEndSalon.IngresarSalon()){
                    LimpiarCampos("add");
                    UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                } else lblError.setText(
                    "<html><p style=\"text-align:center\">Hubo un error al ingresar el salón. "
                            + "Por favor inténtelo de nuevo.</p></html>");
            } else lblError.setText(
                "<html><p style=\"text-align:center\">Ya existe un salón con ese nombre.</p></html>");
        } else lblError.setText(
            "<html><p style=\"text-align:center\">Uno de los campos ingresados está vacío.</p></html>");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditCapacidad1;
    private javax.swing.JTextField EditDescripcion;
    private javax.swing.JComboBox<String> EditEstado;
    private javax.swing.JTextField EditNombre;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel editBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel sombra;
    private javax.swing.JLabel sombraAceptar;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
