/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josué Lacayo
 */
public class OtrosFacturacion extends javax.swing.JPanel {
    //Declaración de variables
    int modoeditar = 0;
    DefaultTableModel modelo = new DefaultTableModel();
    
    int membresia = 0;
    
    char genero = 'G';
    int paso = 0;
    
    String query1;
    String query2;    
    
    /**
     * Creates new form OtrosFacturacion
     */
    public OtrosFacturacion() {
        initComponents();
        //se modifica la tabla para mostrar los datos del usuario
        modelo.addColumn("No.");
        modelo.addColumn("Nombres");
        modelo.addColumn("Usuario");
        modelo.addColumn("Email");
        modelo.addColumn("Dui");
        modelo.addColumn("Telefono");
        modelo.addColumn("Membresía");
        Tabla.setModel(modelo);
        //Placeholders para los textBoxs
        new ThirdLayer.PTextField.GhostText(txtUsuario, "Usuario");
        new ThirdLayer.PTextField.GhostText(txtMembresia, "Membresía");
        new ThirdLayer.PTextField.GhostText(txtCorreo, "E-Mail");
        //Consulta para mostrar los datos en la tabla 
        query1 = "SELECT c.idusuario, (u.nombres+' '+u.apellidos), u.usuario, u.email, u.dui, u.telefono, m.tipo " +
        "FROM Usuario u, Membresias m, Cliente c " +
        "WHERE u.idusuario = c.idusuario AND c.idmembresia = m.idmembresia AND u.idtipousuario = 5;";
        query2 = "SELECT c.idusuario, (u.nombres+' '+u.apellidos), u.usuario, u.email, u.dui, u.direccion, u.telefono, m.tipo "+
        "FROM Usuario u, Membresias m, Cliente c " +
        "WHERE u.idusuario = c.idusuario AND c.idmembresia = m.idmembresia " + 
        "AND u.idtipousuario = 5 AND (u.nombres+' '+u.apellidos) LIKE ?";
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        txtPagoAtrasado.setVisible(false);
        lblPagoAtrasdo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPagoAtrasdo = new javax.swing.JLabel();
        txtPagoAtrasado = new javax.swing.JTextField();
        txtUltimaFecha = new javax.swing.JLabel();
        llblFecha = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        txtMembresia = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtPagar = new javax.swing.JTextField();
        txtPagando = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtDUI = new javax.swing.JFormattedTextField();
        lblAdvertencia = new javax.swing.JLabel();
        barrabuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        textoflitros = new javax.swing.JLabel();
        btnMemPremium = new javax.swing.JLabel();
        btnMemEst = new javax.swing.JLabel();
        lblDolar2 = new javax.swing.JLabel();
        lblDolar1 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        filtrosBack = new javax.swing.JLabel();
        datosBack = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        sombraImprimir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1715));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPagoAtrasdo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPagoAtrasdo.setForeground(new java.awt.Color(153, 153, 153));
        lblPagoAtrasdo.setText("<html><p style:\"text-align= center;\"\">+ atraso en el pago: $</p></html>");
        add(lblPagoAtrasdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1330, 250, 60));

        txtPagoAtrasado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPagoAtrasado.setForeground(new java.awt.Color(0, 0, 0));
        txtPagoAtrasado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagoAtrasado.setBorder(null);
        txtPagoAtrasado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPagoAtrasado.setEnabled(false);
        txtPagoAtrasado.setOpaque(false);
        add(txtPagoAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 1340, 70, 40));

        txtUltimaFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtUltimaFecha.setForeground(new java.awt.Color(153, 153, 153));
        add(txtUltimaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 1430, 170, 40));

        llblFecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        llblFecha.setForeground(new java.awt.Color(153, 153, 153));
        llblFecha.setText("<html><p style:\"text-align= center;\"\">El último pago fue realizado: </p></html>");
        add(llblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1420, 320, 60));

        txtCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCambio.setForeground(new java.awt.Color(0, 0, 0));
        txtCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCambio.setBorder(null);
        txtCambio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCambio.setEnabled(false);
        txtCambio.setOpaque(false);
        add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1430, 70, 40));

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setBorder(null);
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setEnabled(false);
        txtApellidos.setOpaque(false);
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 1055, 420, 40));

        txtNombres.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setBorder(null);
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setEnabled(false);
        txtNombres.setOpaque(false);
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1055, 420, 40));

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 730, 40));

        txtMembresia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtMembresia.setForeground(new java.awt.Color(0, 0, 0));
        txtMembresia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMembresia.setBorder(null);
        txtMembresia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMembresia.setEnabled(false);
        txtMembresia.setOpaque(false);
        add(txtMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1240, 190, 50));

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setBorder(null);
        txtCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setEnabled(false);
        txtCorreo.setOpaque(false);
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1240, 310, 50));

        txtPagar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtPagar.setForeground(new java.awt.Color(0, 0, 0));
        txtPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagar.setBorder(null);
        txtPagar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPagar.setEnabled(false);
        txtPagar.setOpaque(false);
        add(txtPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1335, 140, 50));

        txtPagando.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtPagando.setForeground(new java.awt.Color(0, 0, 0));
        txtPagando.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPagando.setBorder(null);
        txtPagando.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPagando.setEnabled(false);
        txtPagando.setOpaque(false);
        txtPagando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagandoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagandoKeyTyped(evt);
            }
        });
        add(txtPagando, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1430, 140, 50));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(null);
        txtUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsuario.setEnabled(false);
        txtUsuario.setOpaque(false);
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1240, 190, 50));

        txtTelefono.setBorder(null);
        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setToolTipText("");
        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefono.setEnabled(false);
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtTelefono.setOpaque(false);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1145, 190, 50));

        txtDUI.setBorder(null);
        try {
            txtDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDUI.setToolTipText("");
        txtDUI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDUI.setEnabled(false);
        txtDUI.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtDUI.setOpaque(false);
        add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1145, 400, 50));

        lblAdvertencia.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblAdvertencia.setForeground(new java.awt.Color(255, 0, 0));
        lblAdvertencia.setText("<html><p style:\"text-align= center;\"\"></p></html>");
        add(lblAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1570, 740, 50));

        barrabuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra de búsqueda.png"))); // NOI18N
        add(barrabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 1140, 80));

        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Botón buscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 200, 60));

        textoflitros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Filtros.png"))); // NOI18N
        add(textoflitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 60));

        btnMemPremium.setToolTipText("");
        btnMemPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMemPremiumMouseClicked(evt);
            }
        });
        add(btnMemPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 510, 60));

        btnMemEst.setToolTipText("");
        btnMemEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMemEstMouseClicked(evt);
            }
        });
        add(btnMemEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 510, 60));

        lblDolar2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblDolar2.setForeground(new java.awt.Color(153, 153, 153));
        lblDolar2.setText("<html><p style:\"text-align= center;\"\">$</p></html>");
        add(lblDolar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1440, 20, 30));

        lblDolar1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblDolar1.setForeground(new java.awt.Color(153, 153, 153));
        lblDolar1.setText("<html><p style:\"text-align= center;\"\">$</p></html>");
        add(lblDolar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1345, 20, 30));

        lblCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(153, 153, 153));
        lblCambio.setText("<html><p style:\"text-align= center;\"\">El cambio a entregar es de: $</p></html>");
        add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1420, 330, 60));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 1150, 680));

        filtrosBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/Filtro facturación.png"))); // NOI18N
        add(filtrosBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 1020, 60));

        datosBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/Campos de datos.png"))); // NOI18N
        add(datosBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1040, 1210, 450));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/Botón imprimir.png"))); // NOI18N
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimirMouseClicked(evt);
            }
        });
        add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1570, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1580, -1, 40));

        sombraImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/sombra imprimir.png"))); // NOI18N
        add(sombraImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //Recargar tabla con una consulta específica
    private void RecargarTablaEspecifica(){
        try {
            modelo.setRowCount(0);
            String query = "SELECT c.idusuario, (u.nombres+' '+u.apellidos), u.usuario, u.email, u.dui, u.telefono, m.tipo " +
            "FROM Usuario u, Membresias m, Cliente c " +
            "WHERE u.idusuario = c.idusuario AND c.idmembresia = m.idmembresia AND u.idtipousuario = 5 AND m.idmembresia = ?;";       
            ThirdLayer.BackEnd.FillTablaEspecifico(Tabla, query, membresia);
            System.out.println("Funciona la query");
        } catch (Exception e) {System.out.println("Falló la query: "+e.getMessage());}
    }
    
    //Validaciones de texto
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            getToolkit().beep();
        }
        if(c == KeyEvent.VK_ENTER)
            UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText().trim(), modelo, query2);
        if (txtBuscar.getText().trim().length() <= 1 || txtBuscar.getText().trim().isEmpty())
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
    }//GEN-LAST:event_txtBuscarKeyTyped
    //Eventos
    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText().trim(), modelo, query2);
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (modoeditar == 1){}
            Regresar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        Editar();
    }//GEN-LAST:event_TablaMouseClicked

    private void btnMemEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemEstMouseClicked
        membresia = 2;
        btnMemEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/Membresía estándar-1.png")));
        btnMemPremium.setIcon(null);
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnMemEstMouseClicked

    private void btnMemPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemPremiumMouseClicked
        membresia = 1;
        btnMemEst.setIcon(null);
        btnMemPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Facturación/Membresía premium-1.png")));
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnMemPremiumMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        membresia = 0;
        btnMemEst.setIcon(null);
        btnMemPremium.setIcon(null);
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
    }//GEN-LAST:event_formMouseClicked
    //Validaciones de texto
    private void txtPagandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagandoKeyReleased
        txtCambio.setText("");
        lblAdvertencia.setText("");
        if (!txtPagando.getText().trim().isEmpty()){
            Double pagar = Double.valueOf(txtPagar.getText());
            String texto = txtPagando.getText().trim();
            Double pagando = Double.parseDouble(texto);
            if (pagando >= pagar){
                Double resultado = (pagando - pagar);
                txtCambio.setText(""+resultado);
                lblAdvertencia.setText("");
                paso = 1;
            } else {
                lblAdvertencia.setText(
                    "<html><p style:\"text-align=center;\">El valor a pagar es menor que el costo de la membresía.</p></html>");
                txtCambio.setText("");
                paso = 0;
            }
            if (txtPagando.getText().trim().length() < 1 || txtPagando.getText().trim().isEmpty())
                txtCambio.setText("");
        }
    }//GEN-LAST:event_txtPagandoKeyReleased

    private void txtPagandoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagandoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_PERIOD || c == KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtPagandoKeyTyped
    //Guardar e imprimir la factura
    private void btnImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseClicked
        String fecha = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
        String[] SFecha1 = fecha.split("-", 3);
        String[] SFecha2;
        
        boolean primeravez = false;
        if (!txtUltimaFecha.getText().equals("Nunca"))
            SFecha2 = txtUltimaFecha.getText().split("-", 3);
        else {
            SFecha2 = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()).split("-", 3);
            primeravez = true;
        }
        
        Integer[] FechaInt1 = new Integer[SFecha1.length];
        Integer[] FechaInt2 = new Integer[SFecha2.length];
        
        int i = 0;
        for (String f : SFecha1) {
            FechaInt1[i] = Integer.parseInt(f);
            i++;
        }
        
        int i2 =0;
        for (String f : SFecha2) {
            FechaInt2[i2] = Integer.parseInt(f);
            i2++;
        }
        
        if (paso == 1){
            if (
                    (
                        (FechaInt1[0] >= FechaInt2[0]) /*2019-09-21, 2019-10-21*/ 
                        &&
                        (FechaInt1[1] > FechaInt2[1])
                        &&
                        (FechaInt1[2] >= FechaInt2[2])
                    ) || primeravez == true
                )
            {
                ThirdLayer.BackEndFacturacion.setMonto(Double.valueOf(txtPagar.getText()));
                ThirdLayer.BackEndFacturacion.setCancelado(Double.valueOf(txtPagando.getText()));
                ThirdLayer.BackEndFacturacion.setDevuelto(Double.valueOf(txtCambio.getText()));
                ThirdLayer.BackEndFacturacion.setFechapago(fecha);
                ThirdLayer.BackEndFacturacion.setIdcliente(ThirdLayer.BackEndFacturacion.getIdcliente());
                if(ThirdLayer.BackEndFacturacion.IngresarFactura()){
                    Regresar();
                    java.util.Map parameters = new HashMap();
                    parameters.put("Factura", ThirdLayer.BackEndFacturacion.getIdfactura());
                    Reportes.ImprimirReporte("Reportes/ReporteFactura.jrxml",parameters,"Factura de Pago");
                } else lblAdvertencia.setText(
                        "<html><p style:\"text-align=center;\">Un error ha ocurrido. Por favor inténtelo de nuevo.</p></html>");
            } else lblAdvertencia.setText(
                    "<html><p style:\"text-align=center;\">El pago anterior aún es válido. "
                            + "Por favor intentélo de nuevo más tarde</p></html>");
        } else lblAdvertencia.setText(
                "<html><p style:\"text-align=center;\">Por favor ingrese los datos solicitados correctamente.</p></html>");
    }//GEN-LAST:event_btnImprimirMouseClicked
    //Eventos
    private void Regresar(){
        if(modoeditar == 1) {
            OtrosFramePrincipal.SeeUserMove1();
            LimpiarCampos();
            cambiarEstado(false);
            modoeditar = 0;
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        }
    }
    //Limpiar campos de texto
    private void LimpiarCampos(){
        txtCambio.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtDUI.setText("");
        txtPagando.setText("");
        txtUsuario.setText("");
        txtPagar.setText("");
        txtCorreo.setText("");
        txtMembresia.setText("");
    }
    //Cambiar estado de los objetos en pantalla
    private void cambiarEstado(boolean value){
//        txtNombres.setEnabled(value);
//        txtApellidos.setEnabled(value);
//        txtTelefono.setEnabled(value);
//        txtDUI.setEnabled(value);
        txtPagando.setEnabled(value);
//        txtUsuario.setEnabled(value);
//        txtPagar.setEnabled(value);
//        txtCorreo.setEnabled(value);
//        txtMembresia.setEnabled(value);
        btnCancelar.setEnabled(value);
        btnImprimir.setEnabled(value);
        sombraImprimir.setEnabled(value);
        if (value == false){
            lblPagoAtrasdo.setVisible(value);
            txtPagoAtrasado.setVisible(value);
        }
    }
    //Editar el usuario seleccionado
    private void Editar(){
        if (Tabla.getSelectedRow() != -1){
            modoeditar = 1;
            ThirdLayer.BackEndFacturacion.GetUserInformation((Integer) Tabla.getValueAt(Tabla.getSelectedRow(), 0));
            txtNombres.setText(ThirdLayer.BackEndFacturacion.getNombres());
            txtApellidos.setText(ThirdLayer.BackEndFacturacion.getApellidos());
            txtTelefono.setText(ThirdLayer.BackEndFacturacion.getTelefono());
            txtDUI.setText(ThirdLayer.BackEndFacturacion.getDui());
            txtUsuario.setText(ThirdLayer.BackEndFacturacion.getUsuario());
            txtMembresia.setText(ThirdLayer.BackEndFacturacion.getTipo());
            txtCorreo.setText(ThirdLayer.BackEndFacturacion.getEmail());
            txtPagar.setText(String.valueOf(ThirdLayer.BackEndFacturacion.getCosto()));
            System.out.println(ThirdLayer.BackEndFacturacion.getFechapago());
            if (!ThirdLayer.BackEndFacturacion.getFechapago().trim().isEmpty())
                txtUltimaFecha.setText(ThirdLayer.BackEndFacturacion.getFechapago());
            else txtUltimaFecha.setText("Nunca");
            
            String[] SFecha1 = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()).split("-", 3);
            String[] SFecha2;

            if (!txtUltimaFecha.getText().equals("Nunca"))
                SFecha2 = txtUltimaFecha.getText().split("-", 3);
            else 
                SFecha2 = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()).split("-", 3);

            Integer[] FechaInt1 = new Integer[SFecha1.length];
            Integer[] FechaInt2 = new Integer[SFecha2.length];

            int i = 0;
            for (String f : SFecha1) {
                FechaInt1[i] = Integer.parseInt(f);
                i++;
            }

            int i2 =0;
            for (String f : SFecha2) {
                FechaInt2[i2] = Integer.parseInt(f);
                i2++;
            }

            if (
                (FechaInt1[0] >= FechaInt2[0])
                &&
                (FechaInt1[1] > FechaInt2[1])
                &&
                (FechaInt1[2] > FechaInt2[2])
            ){
                txtPagoAtrasado.setVisible(true);
                lblPagoAtrasdo.setVisible(true);
                double pagomora = Double.valueOf(txtPagar.getText());
                txtPagar.setText(String.valueOf(pagomora + 5.00));
                txtPagoAtrasado.setText("5.00");
            }
            cambiarEstado(true);
            OtrosFramePrincipal.AddUserMover1();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel barrabuscar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnImprimir;
    private javax.swing.JLabel btnMemEst;
    private javax.swing.JLabel btnMemPremium;
    private javax.swing.JLabel datosBack;
    private javax.swing.JLabel filtrosBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblDolar1;
    private javax.swing.JLabel lblDolar2;
    private javax.swing.JLabel lblPagoAtrasdo;
    private javax.swing.JLabel llblFecha;
    private javax.swing.JLabel sombraImprimir;
    private javax.swing.JLabel textoflitros;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtDUI;
    private javax.swing.JTextField txtMembresia;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPagando;
    private javax.swing.JTextField txtPagar;
    private javax.swing.JTextField txtPagoAtrasado;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JLabel txtUltimaFecha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
