/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Josue Lacayo
 */
public class OtrosMembresias extends javax.swing.JPanel {

    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    int membresia = 1;
    
    
    /**
     * Creates new form membresias
     */
    public OtrosMembresias() {
        initComponents();
        UsuarioFormularioPrincipal.CurrentTime(lblHora, lblMes, lblDia);
        UsuarioFormularioPrincipal.NivelUsuario(lblNombre, lblNivel);
        lblLEditar.setVisible(false);
        lblLAgregar.setVisible(false);
        panelVariable.getVerticalScrollBar().setUnitIncrement(20);
        modelo.addColumn("No.");
        modelo.addColumn("Nombres");
        modelo.addColumn("ID");
        modelo.addColumn("Estado");
        modelo.addColumn("Membresía");
        Tabla.setModel(modelo);
        RecargarTabla();
    }
    //Recargar tabla con una query especifica
    private void RecargarTablaEspecifica(){
        try {
            modelo.setRowCount(0);
            String query = "SELECT c.idcliente, (u.nombres+' '+u.apellidos), u.idusuario, e.estado, m.tipo "
                    + "FROM Cliente c, Membresias m, Usuario u, EstadoUsuario e "
                    + "WHERE c.idusuario = u.idusuario AND c.idmembresia = m.idmembresia "
                    + "AND e.idestado = u.idestado AND m.idmembresia = ?";
            ThirdLayer.BackEnd.FillTablaEspecifico(Tabla, query, membresia);
        } catch (Exception e) {}
    }
    //Recargar la tabla con datos generales
    private void RecargarTabla(){
        try {
            modelo.setRowCount(0);
            String query = "SELECT c.idcliente, (u.nombres+' '+u.apellidos), u.idusuario, e.estado, m.tipo "
                    + "FROM Cliente c, Membresias m, Usuario u, EstadoUsuario e "
                    + "WHERE c.idusuario = u.idusuario AND c.idmembresia = m.idmembresia "
                    + "AND e.idestado = u.idestado";
            ThirdLayer.BackEnd.FillTablaGeneral(Tabla, query);
        } catch (Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVariable = new javax.swing.JScrollPane();
        panelModificable = new javax.swing.JPanel();
        btnEstandar = new javax.swing.JLabel();
        btnPremium = new javax.swing.JLabel();
        sombrapremium = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        sombraestandar = new javax.swing.JLabel();
        lblMembresias = new javax.swing.JLabel();
        lblLVisualizar = new javax.swing.JLabel();
        lblLAgregar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblLEditar = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        fondoUsuario = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        sombracerrar = new javax.swing.JLabel();
        barrarriba = new javax.swing.JLabel();
        menulateral1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVariable.setPreferredSize(new java.awt.Dimension(1467, 980));
        panelVariable.setRequestFocusEnabled(false);

        panelModificable.setBackground(new java.awt.Color(255, 255, 255));
        panelModificable.setPreferredSize(new java.awt.Dimension(1467, 1578));
        panelModificable.setRequestFocusEnabled(false);
        panelModificable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelModificableMousePressed(evt);
            }
        });
        panelModificable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Membresía estándar.png"))); // NOI18N
        btnEstandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstandarMouseClicked(evt);
            }
        });
        panelModificable.add(btnEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        btnPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Membresía premium.png"))); // NOI18N
        btnPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPremiumMouseClicked(evt);
            }
        });
        panelModificable.add(btnPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        sombrapremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Sombra membresía premium.png"))); // NOI18N
        panelModificable.add(sombrapremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 730, -1));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabla);

        panelModificable.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 1300, 1040));

        sombraestandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Sombra membresía estándar.png"))); // NOI18N
        panelModificable.add(sombraestandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        panelVariable.setViewportView(panelModificable);

        add(panelVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 1490, -1));

        lblMembresias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitácoras/Membresías.png"))); // NOI18N
        add(lblMembresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 15, -1, -1));

        lblLVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Visualizar.png"))); // NOI18N
        lblLVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLVisualizarMouseClicked(evt);
            }
        });
        add(lblLVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        lblLAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Agregar.png"))); // NOI18N
        lblLAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLAgregarMouseClicked(evt);
            }
        });
        add(lblLAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 15, 222, 71));

        lblLEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Editar.png"))); // NOI18N
        lblLEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLEditarMouseClicked(evt);
            }
        });
        add(lblLEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        lblNivel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, 40));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 50));

        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Cuadro para usaurio y nivel.png"))); // NOI18N
        add(fondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblDia.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        lblDia.setForeground(new java.awt.Color(0, 0, 0));
        add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 85, 64));

        lblMes.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblMes.setForeground(new java.awt.Color(0, 0, 0));
        lblMes.setToolTipText("");
        add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 50));

        lblHora.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setToolTipText("");
        add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 33, 130, 39));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Atrás.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Botón cerrar.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 25, -1, -1));

        sombracerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Sombra cerrar.png"))); // NOI18N
        add(sombracerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 0, -1, -1));

        barrarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Barra de arriba.png"))); // NOI18N
        add(barrarriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menulateral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Menú lateral.png"))); // NOI18N
        add(menulateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void lblLVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLVisualizarMouseClicked
//        UsuarioFormularioPrincipal.Move(new UsuarioSeeUsuario(), 3);
//        lblLVisualizar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Visualizar-H.png")
//            )
//        );
//        lblLEditar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Editar.png")
//            )
//        );
//        lblLAgregar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Agregar.png")
//            )
//        );
    }//GEN-LAST:event_lblLVisualizarMouseClicked

    private void lblLAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLAgregarMouseClicked
//        UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
//        lblLAgregar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Agregar-H.png")
//            )
//        );
//        lblLVisualizar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Visualizar.png")
//            )
//        );
//        lblLEditar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Editar.png")
//            )
//        );
    }//GEN-LAST:event_lblLAgregarMouseClicked

    private void lblLEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLEditarMouseClicked
//        UsuarioFormularioPrincipal.Move(new UsuarioEditUsuario(), 2);
//        lblLEditar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Editar-H.png")
//            )
//        );
//        lblLAgregar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Agregar.png")
//            )
//        );
//        lblLVisualizar.setIcon(
//            new javax.swing.ImageIcon(getClass().
//                getResource("/UsuarioAssets/Visualizar.png")
//            )
//        );
    }//GEN-LAST:event_lblLEditarMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        FramePrincipal.Move(new MenuPrincipal());
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPremiumMouseClicked
        membresia = 1;
        RecargarTablaEspecifica();
        btnPremium.setEnabled(false);
        sombrapremium.setEnabled(false);
        btnEstandar.setEnabled(true);
        sombraestandar.setEnabled(true);
    }//GEN-LAST:event_btnPremiumMouseClicked

    private void btnEstandarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstandarMouseClicked
        membresia = 2;
        RecargarTablaEspecifica();
        btnPremium.setEnabled(true);
        sombrapremium.setEnabled(true);
        btnEstandar.setEnabled(false);
        sombraestandar.setEnabled(false);
    }//GEN-LAST:event_btnEstandarMouseClicked

    private void panelModificableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModificableMousePressed
        membresia = 0;
        RecargarTabla();
        btnPremium.setEnabled(true);
        sombrapremium.setEnabled(true);
        btnEstandar.setEnabled(true);
        sombraestandar.setEnabled(true);
    }//GEN-LAST:event_panelModificableMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel barrarriba;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnEstandar;
    private javax.swing.JLabel btnPremium;
    private javax.swing.JLabel fondoUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblLAgregar;
    public static javax.swing.JLabel lblLEditar;
    public static javax.swing.JLabel lblLVisualizar;
    private javax.swing.JLabel lblMembresias;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel menulateral1;
    public static javax.swing.JPanel panelModificable;
    private javax.swing.JScrollPane panelVariable;
    private javax.swing.JLabel sombracerrar;
    private javax.swing.JLabel sombraestandar;
    private javax.swing.JLabel sombrapremium;
    // End of variables declaration//GEN-END:variables
}
