/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import java.awt.HeadlessException;


/**
 *
 * @author Josue Lacayo
 */
public class OtrosConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form configuracion
     */
    public OtrosConfiguracion() {
        initComponents();
    }
    //Declaración de variables
    String path = null;
    String FileName;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo2 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JLabel();
        btnRestore = new javax.swing.JLabel();
        lblBackup = new javax.swing.JLabel();
        lblRestore = new javax.swing.JLabel();
        lblElegir = new javax.swing.JLabel();
        lblElegir1 = new javax.swing.JLabel();
        lblElegir2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 980));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(255, 0, 51));
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo2.setToolTipText("");
        add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 810, 640, 120));

        lblInfo1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(255, 0, 51));
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setToolTipText("");
        add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 640, 120));

        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/Botón hacer copiaa.png"))); // NOI18N
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackupMousePressed(evt);
            }
        });
        add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        btnRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/Botón restaurar copiaa.png"))); // NOI18N
        btnRestore.setEnabled(false);
        btnRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRestoreMousePressed(evt);
            }
        });
        add(btnRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, -1, -1));

        lblBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/Definición visualizar.png"))); // NOI18N
        add(lblBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        lblRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/Definición visualizar-1.png"))); // NOI18N
        add(lblRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, -1, -1));

        lblElegir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/Elige qué hacer con la copia de seguridad.png"))); // NOI18N
        add(lblElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        lblElegir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/sombra restaurar copia.png"))); // NOI18N
        add(lblElegir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        lblElegir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/sombra restaurar copia.png"))); // NOI18N
        lblElegir2.setEnabled(false);
        add(lblElegir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //Elegir sitio dónde se guardará el backup
    private void btnBackupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMousePressed
        try{
            javax.swing.JFileChooser FC =  new javax.swing.JFileChooser();
            FC.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
            FC.showOpenDialog(this);

            String date = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
            ThirdLayer.BackEndBackup.GetDatabaseName();
            
            java.io.File file = FC.getSelectedFile();
            path = file.getPath();
            //path = path.replace('\\', '/');
            path = path +"\\"+ ThirdLayer.BackEndBackup.getDbName() + "_" + date + ".bak";
            
            System.out.println(path);
            
            ThirdLayer.BackEndBackup.setFilePath(path);
            if (ThirdLayer.BackEndBackup.CrearBackup()){
                lblInfo1.setForeground(new java.awt.Color(51,204,0));
                lblInfo1.setText(
                        "<html><p style=\"style-align:center;\">El backup fue guardado éxitosamente en: "
                                + "\""+path+"\".</p></html>");
            }
        } catch (HeadlessException e) {
            lblInfo1.setText(
                        "<html><p style=\"style-align:center;\">Error al guardar el backup: \""+e.getLocalizedMessage()
                                +"\".</p></html>");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBackupMousePressed
    //Botón que elige el archivo para restaurar el backup
    private void btnRestoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMousePressed
        if (btnRestore.isEnabled() == true){
            try{
                javax.swing.JFileChooser FC =  new javax.swing.JFileChooser();
                FC.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
                FC.showOpenDialog(this);
                java.io.File file = FC.getCurrentDirectory();
                path = file.getAbsolutePath();
                //path = path.replace('\\', '/');
                ThirdLayer.BackEndBackup.setFilePath(path);
                if (ThirdLayer.BackEndBackup.RestaurarBackup()){
                    lblInfo1.setForeground(new java.awt.Color(51,204,0));
                    lblInfo1.setText(
                            "<html><p style=\"style-align:center;\">El backup fue restaurado éxitosamente.</p></html>");
                }
            } catch (HeadlessException e) {
                lblInfo1.setText(
                            "<html><p style=\"style-align:center;\">Error al restaurar el backup: \""+e.getLocalizedMessage()
                                    +"\".</p></html>");
            }
        } else lblInfo2.setText(
                        "<html><p style=\"style-align:center;\">Actualmente no se puede restaurar una versión anterior. "
                                + "Favor de ponerse en contacto con el servicio técnico de FitLogic.</p></html>");
    }//GEN-LAST:event_btnRestoreMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackup;
    private javax.swing.JLabel btnRestore;
    private javax.swing.JLabel lblBackup;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblElegir1;
    private javax.swing.JLabel lblElegir2;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblRestore;
    // End of variables declaration//GEN-END:variables
}
