/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Josue Lacayo
 */
public class OtrosFramePrincipal extends javax.swing.JPanel {
    //Declaración de variables
    int modoeditar = 0;
    int nivel = 0;
    DefaultTableModel modelo1 = new DefaultTableModel();
    
    int membresia = 0;
    
    char genero = 'G';
    int estadou = 0;
    
    String query1;
    
    /**
     * 
     * 
     */
    public OtrosFramePrincipal() {
        initComponents();
        lblBackup.setVisible(false);
        PanelMovible.getVerticalScrollBar().setUnitIncrement(20);
        UsuarioFormularioPrincipal.CurrentTime(lblHora,lblMes,lblDia);
        UsuarioFormularioPrincipal.NivelUsuario(lblNombre, lblNivel);
    }
    //Visualizar los paneles en el panel movible
    public static void Move (javax.swing.JPanel p, int type){
        int y = 0;
        switch (type){
            case 1:
                y = 1715;
                break;
            case 2:
                y = 1960;
                break;
            case 3:
                y = 2960;
                break;
            case 4:
                y = 980;
                lblBackup.setVisible(true);
                lblLSalones.setVisible(false);
                lblLFacturacion.setVisible(false);
                lblLIndumentaria.setVisible(false);
                break;
        }
        
        panelModificable.setPreferredSize(new java.awt.Dimension(1467, y));
        PanelMovible.getVerticalScrollBar().setValue(0);
        p.setSize(1467, y);
        p.setLocation(0, 0);
        
        panelModificable.removeAll();
        panelModificable.add(p, java.awt.BorderLayout.CENTER);
        panelModificable.revalidate();
        panelModificable.repaint();
    }
    //Mover hacia abajo hasta 730px
    public static void AddUserMover1(){
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                while (PanelMovible.getVerticalScrollBar().getValue() < 730){
                    PanelMovible.getVerticalScrollBar().setValue(
                            PanelMovible.getVerticalScrollBar().getValue()+1);
                }
            }
        }, 0);
        new java.util.Timer().cancel();
    }
    //Mover hacia abajo hasta 1954px
    public static void AddUserMover2(){
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                while (PanelMovible.getVerticalScrollBar().getValue() < 1953){
                    PanelMovible.getVerticalScrollBar().setValue(
                            PanelMovible.getVerticalScrollBar().getValue()+1);
                }
            }
        }, 0);
        new java.util.Timer().cancel();
    }
    //Mover hacia arriba
    public static void SeeUserMove1(){
        new java.util.Timer().schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                while (PanelMovible.getVerticalScrollBar().getValue() > 0){
                    PanelMovible.getVerticalScrollBar().setValue(
                            PanelMovible.getVerticalScrollBar().getValue()-1);
                }
            }
        }, 0);
        new java.util.Timer().cancel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackup = new javax.swing.JLabel();
        clases = new javax.swing.JLabel();
        lblLFacturacion = new javax.swing.JLabel();
        lblLIndumentaria = new javax.swing.JLabel();
        lblLSalones = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        fondoUsuario = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        sombracerrar = new javax.swing.JLabel();
        barrarriba = new javax.swing.JLabel();
        menulateral = new javax.swing.JLabel();
        PanelMovible = new javax.swing.JScrollPane();
        panelModificable = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backups/backup barra.png"))); // NOI18N
        lblBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackupMouseClicked(evt);
            }
        });
        add(lblBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));
        add(clases, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 15, 370, 71));

        lblLFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Facturación.png"))); // NOI18N
        lblLFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLFacturacionMouseClicked(evt);
            }
        });
        add(lblLFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        lblLIndumentaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salones/Indumentaria.png"))); // NOI18N
        lblLIndumentaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLIndumentariaMouseClicked(evt);
            }
        });
        add(lblLIndumentaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        lblLSalones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Salones.png"))); // NOI18N
        lblLSalones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLSalones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLSalonesMouseClicked(evt);
            }
        });
        add(lblLSalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        lblNivel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, 40));

        lblNombre.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 50));

        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Cuadro para usaurio y nivel.png"))); // NOI18N
        add(fondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblDia.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        lblDia.setForeground(new java.awt.Color(0, 0, 0));
        add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 85, 64));

        lblMes.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblMes.setForeground(new java.awt.Color(0, 0, 0));
        lblMes.setToolTipText("");
        add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 50));

        lblHora.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setToolTipText("");
        add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 33, 130, 39));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Atrás.png"))); // NOI18N
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Botón cerrar.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 25, -1, -1));

        sombracerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Sombra cerrar.png"))); // NOI18N
        add(sombracerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 0, -1, -1));

        barrarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Barra de arriba.png"))); // NOI18N
        add(barrarriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menulateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Menú lateral.png"))); // NOI18N
        add(menulateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelMovible.setPreferredSize(new java.awt.Dimension(1470, 980));

        panelModificable.setPreferredSize(new java.awt.Dimension(1467, 1578));

        javax.swing.GroupLayout panelModificableLayout = new javax.swing.GroupLayout(panelModificable);
        panelModificable.setLayout(panelModificableLayout);
        panelModificableLayout.setHorizontalGroup(
            panelModificableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1474, Short.MAX_VALUE)
        );
        panelModificableLayout.setVerticalGroup(
            panelModificableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1578, Short.MAX_VALUE)
        );

        PanelMovible.setViewportView(panelModificable);

        add(PanelMovible, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 1490, 980));
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void lblLFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLFacturacionMouseClicked
        Move(new OtrosFacturacion(), 1);
        lblLFacturacion.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Facturación.png")
            )
        );
        lblLIndumentaria.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Indumentaria.png")
            )
        );
        lblLSalones.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Salones.png")
            )
        );
        clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Facturación-1.png")
            )
        );
    }//GEN-LAST:event_lblLFacturacionMouseClicked
    //Recargar tabla
    public static void RecargarTabla(javax.swing.JTable Tabla, DefaultTableModel modelo, String query){
        try {
            modelo.setRowCount(0);
            ThirdLayer.BackEnd.FillTablaGeneral(Tabla, query);
            System.out.println("Funciona la query");
        } catch (Exception e) {System.out.println("Fallo la query");}
    }
    //Eventos
    private void lblLIndumentariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLIndumentariaMouseClicked
        Move(new OtrosIndumentaria(), 1);
        lblLFacturacion.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Facturación.png")
            )
        );
        lblLIndumentaria.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Indumentaria-1.png")
            )
        );
        lblLSalones.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Salones.png")
            )
        );
        clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Indumentaria.png")
            )
        );
    }//GEN-LAST:event_lblLIndumentariaMouseClicked

    private void lblLSalonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLSalonesMouseClicked
        Move(new OtrosSalones(), 1);
        lblLFacturacion.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Indumentaria/Facturación.png")
            )
        );
        lblLIndumentaria.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Facturación/Indumentaria.png")
            )
        );
        lblLSalones.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Salones/Salones.png")
            )
        );
        clases.setIcon(
            new javax.swing.ImageIcon(getClass().
                getResource("/Salones/Salones-1.png")
            )
        );
    }//GEN-LAST:event_lblLSalonesMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        FramePrincipal.Move(new MenuPrincipal());
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void lblBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBackupMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane PanelMovible;
    private javax.swing.JLabel barrarriba;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnCerrar;
    public static javax.swing.JLabel clases;
    private javax.swing.JLabel fondoUsuario;
    public static javax.swing.JLabel lblBackup;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblLFacturacion;
    public static javax.swing.JLabel lblLIndumentaria;
    public static javax.swing.JLabel lblLSalones;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel menulateral;
    public static javax.swing.JPanel panelModificable;
    private javax.swing.JLabel sombracerrar;
    // End of variables declaration//GEN-END:variables
}
