/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davidmorataya
 */
public class OtrosIndumentaria extends javax.swing.JPanel {
    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    
    String query1;
    
    int modoeditar = 0;

    /**
     * Creates new form Indumentaria
     */
    public OtrosIndumentaria() {
        initComponents();
        //Placeholders de los campos de texto
        new ThirdLayer.PTextField.GhostText(txtNombre, "Nombre");
        new ThirdLayer.PTextField.GhostText(txtDescripcion, "Descripción");
        new ThirdLayer.PTextField.GhostText(txtCantidad, "Cantidad");
        new ThirdLayer.PTextField.GhostText(EditNombre, "Nombre");
        new ThirdLayer.PTextField.GhostText(EditDescripcion, "Descripción");
        new ThirdLayer.PTextField.GhostText(EditCantidad, "Cantidad");
        
        query1 = "SELECT te.idtipoequipamiento, te.tipo, te.descripcion, te.estado, e.cantidad "
                + "FROM TipoEquipamiento te, Equipamiento e WHERE te.idtipoequipamiento = e.idtipoequipo";
        //Modelo
        modelo.addColumn("ÏD");
        modelo.addColumn("Tipo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Estado");
        modelo.addColumn("Cantidad");
        Tabla.setModel(modelo);
        //Rellenar los comboBoxes
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        
        cbxEstado.removeAllItems();
        EditEstado.removeAllItems();
        
        cbxEstado.addItem("Activo");
        cbxEstado.addItem("Inactivo");
        cbxEstado.addItem("Mantenimiento");
        cbxEstado.setSelectedIndex(-1);
        
        EditEstado.addItem("Activo");
        EditEstado.addItem("Inactivo");
        EditEstado.addItem("Mantenimiento");
        EditEstado.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditError = new javax.swing.JLabel();
        EditEstado = new javax.swing.JComboBox<>();
        EditCantidad = new javax.swing.JTextField();
        EditDescripcion = new javax.swing.JTextField();
        EditNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        sombra = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        sombraAceptar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnCancelar = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1715));
        setLayout(null);

        lblEditError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEditError.setForeground(new java.awt.Color(255, 0, 51));
        lblEditError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditError.setToolTipText("");
        add(lblEditError);
        lblEditError.setBounds(980, 1480, 370, 100);

        EditEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EditEstado.setBorder(null);
        EditEstado.setEnabled(false);
        EditEstado.setOpaque(false);
        add(EditEstado);
        EditEstado.setBounds(660, 1250, 200, 40);

        EditCantidad.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditCantidad.setBorder(null);
        EditCantidad.setEnabled(false);
        EditCantidad.setOpaque(false);
        EditCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditCantidadKeyTyped(evt);
            }
        });
        add(EditCantidad);
        EditCantidad.setBounds(100, 1460, 510, 42);

        EditDescripcion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditDescripcion.setBorder(null);
        EditDescripcion.setEnabled(false);
        EditDescripcion.setOpaque(false);
        EditDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditDescripcionKeyTyped(evt);
            }
        });
        add(EditDescripcion);
        EditDescripcion.setBounds(100, 1360, 760, 42);

        EditNombre.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EditNombre.setBorder(null);
        EditNombre.setEnabled(false);
        EditNombre.setOpaque(false);
        EditNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditNombreKeyTyped(evt);
            }
        });
        add(EditNombre);
        EditNombre.setBounds(100, 1250, 510, 42);

        txtDescripcion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtDescripcion.setBorder(null);
        txtDescripcion.setOpaque(false);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        add(txtDescripcion);
        txtDescripcion.setBounds(100, 235, 750, 42);

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtCantidad.setBorder(null);
        txtCantidad.setOpaque(false);
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        add(txtCantidad);
        txtCantidad.setBounds(100, 340, 500, 42);

        txtNombre.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre);
        txtNombre.setBounds(100, 130, 500, 42);

        cbxEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxEstado.setBorder(null);
        cbxEstado.setOpaque(false);
        add(cbxEstado);
        cbxEstado.setBounds(650, 130, 200, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Visualizar.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(70, 540, 178, 48);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Campos de datos.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(70, 120, 795, 275);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Agregar.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(80, 30, 148, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Editar.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(80, 1170, 108, 48);

        editBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Campos de datos.png"))); // NOI18N
        add(editBack);
        editBack.setBounds(80, 1240, 795, 275);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Definición agregar.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(980, 130, 400, 180);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Definición editar.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(980, 1240, 411, 227);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón agregar.png"))); // NOI18N
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        add(btnAgregar);
        btnAgregar.setBounds(660, 430, 207, 57);

        sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra agregar.png"))); // NOI18N
        add(sombra);
        sombra.setBounds(630, 400, 265, 115);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón aceptar.png"))); // NOI18N
        btnAceptar.setEnabled(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        add(btnAceptar);
        btnAceptar.setBounds(670, 1550, 207, 57);

        sombraAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra aceptar.png"))); // NOI18N
        sombraAceptar.setEnabled(false);
        add(sombraAceptar);
        sombraAceptar.setBounds(640, 1520, 265, 115);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Definición visualizar.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(980, 610, 411, 260);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón editar.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        add(btnEditar);
        btnEditar.setBounds(980, 900, 200, 57);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Botón eliminar.png"))); // NOI18N
        btnEliminar.setEnabled(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(980, 980, 200, 57);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/Sombra eliminar.png"))); // NOI18N
        jLabel14.setEnabled(false);
        add(jLabel14);
        jLabel14.setBounds(960, 960, 248, 105);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Indumentaria/sombra editar.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(900, 830, 356, 213);

        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setToolTipText("");
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tabla);

        add(jScrollPane2);
        jScrollPane2.setBounds(70, 620, 790, 420);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar);
        btnCancelar.setBounds(480, 1560, 124, 34);

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setToolTipText("");
        add(lblError);
        lblError.setBounds(980, 340, 370, 100);
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        Agregar();
    }//GEN-LAST:event_btnAgregarMouseClicked
    //Validaciones de texto
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void EditCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditCantidadKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditCantidadKeyTyped

    private void EditDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditDescripcionKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditDescripcionKeyTyped

    private void EditNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_EditNombreKeyTyped
    
    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (Tabla.getSelectedRow() != -1){
            ThirdLayer.BackEndIndumentaria.GetIndumentaria((Integer) Tabla.getValueAt(Tabla.getSelectedRow(), 0));
            EditNombre.setText(ThirdLayer.BackEndIndumentaria.getTipo());
            EditDescripcion.setText(ThirdLayer.BackEndIndumentaria.getDescripcion());
            switch(ThirdLayer.BackEndIndumentaria.getEstado()){
                case "A":
                    EditEstado.setSelectedItem("Activo");
                    break;
                case "I":
                    EditEstado.setSelectedItem("Inactivo");
                    break;
                case "M":
                    EditEstado.setSelectedItem("Mantenimiento");
                    break;
            }
            EditCantidad.setText(String.valueOf(ThirdLayer.BackEndIndumentaria.getCantidad()));
            modoeditar = 1;
            cambiarEstado(true);
            OtrosFramePrincipal.AddUserMover1();
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (modoeditar == 1)
            Eliminar();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        if (modoeditar == 1)
            Actualizar();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (modoeditar == 1)
            Regresar();
    }//GEN-LAST:event_btnCancelarMouseClicked
    //Regresar
    private void Regresar(){
        if(modoeditar == 1) {
            OtrosFramePrincipal.SeeUserMove1();
            LimpiarCampos("edit");
            cambiarEstado(false);
            modoeditar = 0;
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        }
    }
    //Limpiar campos en pantalla
    private void LimpiarCampos(String tipo){
        if ("edit".equals(tipo)) {
            EditNombre.setText("");
            EditDescripcion.setText("");
            EditCantidad.setText("");
            EditEstado.setSelectedIndex(-1);
        } else if ("add".equals(tipo)){
            txtNombre.setText("");
            txtDescripcion.setText("");
            txtCantidad.setText("");
            cbxEstado.setSelectedIndex(-1);
        }
    }
    //Cambiar el estado de los componentes
    private void cambiarEstado(boolean value){
        editBack.setEnabled(value);
        EditNombre.setEnabled(value);
        EditDescripcion.setEnabled(value);
        EditCantidad.setEnabled(value);
        EditEstado.setEnabled(value);
        btnCancelar.setEnabled(value);
        sombraAceptar.setEnabled(value);
        btnAceptar.setEnabled(value);
        btnEliminar.setEnabled(value);
    }
    //Eliminar una indumentaria
    private void Eliminar(){
        if (Tabla.getSelectedRow() != -1 && modoeditar == 1){
            System.out.println(ThirdLayer.BackEndClases.getIdsalon());
            if (JOptionPane.showConfirmDialog(
                    null, 
                    "¿Desea eliminar la clase?", 
                    "Advertencia", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) 
                    == JOptionPane.YES_OPTION){
                if (ThirdLayer.BackEndIndumentaria.EliminarIndumentaria()){
                       UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                } else JOptionPane.showMessageDialog(null, "No se ha podido eliminar el usuario.", "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    //Actualizar una indumentaria 
    private void Actualizar(){
        System.out.println("N: "+EditNombre.getText()+"\nD: "+EditDescripcion.getText()+"\nC: "+EditCantidad.getText()+
                "\nE: "+EditEstado.getSelectedItem());
        if (!EditNombre.getText().trim().isEmpty() && !EditDescripcion.getText().trim().isEmpty() &&
            !EditCantidad.getText().trim().isEmpty() && EditEstado.getSelectedIndex() != -1&& 
            !("Nombre".equals(EditNombre.getText())) && !("Descripción".equals(EditDescripcion.getText())) &&
            !("Cantidad".equals(EditCantidad.getText()))){
            if((ThirdLayer.BackEndIndumentaria.GetExistingIndumentaria(EditNombre.getText()) == false || 
                ThirdLayer.BackEndIndumentaria.GetExistingIndumentariaId(EditNombre.getText()) == 
                    ThirdLayer.BackEndIndumentaria.getIdtipoequipamiento())){
                ThirdLayer.BackEndIndumentaria.setTipo(EditNombre.getText());
                ThirdLayer.BackEndIndumentaria.setDescripcion(EditDescripcion.getText());
                ThirdLayer.BackEndIndumentaria.setCantidad(Integer.valueOf(EditCantidad.getText()));
                String tipo = "";
                switch(EditEstado.getSelectedIndex()){
                    case 0:
                        tipo = "A";
                        break;
                    case 1:
                        tipo = "I";
                        break;
                    case 2:
                        tipo = "M";
                        break;
                }
                ThirdLayer.BackEndIndumentaria.setEstado(tipo);
                if (ThirdLayer.BackEndIndumentaria.ActualizarIndumentaria()){
                    LimpiarCampos("edit");
                    UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                    OtrosFramePrincipal.SeeUserMove1();
                } else lblEditError.setText(
                    "<html><p style=\"text-align:center\">Hubo un error al ingresar el equipo. "
                            + "Por favor inténtelo de nuevo.</p></html>");
            } else lblEditError.setText(
                "<html><p style=\"text-align:center\">Ya existe un equipo con ese nombre.</p></html>");
        } else lblEditError.setText(
            "<html><p style=\"text-align:center\">Uno de los campos ingresados está vacío.</p></html>");
    }
    //Agregar indumentaria
    private void Agregar(){
        if (!txtNombre.getText().trim().isEmpty() && !txtDescripcion.getText().trim().isEmpty() &&
            !txtCantidad.getText().trim().isEmpty() && cbxEstado.getSelectedIndex() != -1 && 
            !("Nombre".equals(txtNombre.getText())) && !("Descripción".equals(txtDescripcion.getText())) &&
            !("Cantidad".equals(txtCantidad.getText()))){
            if(ThirdLayer.BackEndIndumentaria.GetExistingIndumentaria(txtNombre.getText()) == false){
                ThirdLayer.BackEndIndumentaria.setTipo(txtNombre.getText());
                ThirdLayer.BackEndIndumentaria.setDescripcion(txtDescripcion.getText());
                ThirdLayer.BackEndIndumentaria.setCantidad(Integer.valueOf(txtCantidad.getText()));
                String tipo = "";
                switch(cbxEstado.getSelectedIndex()){
                    case 0:
                        tipo = "A";
                        break;
                    case 1:
                        tipo = "I";
                        break;
                    case 2:
                        tipo = "M";
                        break;
                }
                ThirdLayer.BackEndIndumentaria.setEstado(tipo);
                if (ThirdLayer.BackEndIndumentaria.IngresarIndumentaria()){
                    LimpiarCampos("add");
                    UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
                } else lblError.setText(
                    "<html><p style=\"text-align:center\">Hubo un error al ingresar el equipo. "
                            + "Por favor inténtelo de nuevo.</p></html>");
            } else lblError.setText(
                "<html><p style=\"text-align:center\">Ya existe un equipo con ese nombre.</p></html>");
        } else lblError.setText(
            "<html><p style=\"text-align:center\">Uno de los campos ingresados está vacío.</p></html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditCantidad;
    private javax.swing.JTextField EditDescripcion;
    private javax.swing.JComboBox<String> EditEstado;
    private javax.swing.JTextField EditNombre;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel editBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEditError;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel sombra;
    private javax.swing.JLabel sombraAceptar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
