/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Josue Lacayo
 */
public class RecoverPassword extends javax.swing.JPanel {
    //Declaración de variables
    public static String correo;
    boolean codigoenviado = false;
    /**
     * Creates new form RecuperarContra
     */
    public RecoverPassword() {
        initComponents();
        PanelMovible.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMovible = new javax.swing.JScrollPane();
        panelBasico = new javax.swing.JPanel();
        txtError = new javax.swing.JLabel();
        btnScrollDown = new javax.swing.JLabel();
        FitLogic1 = new javax.swing.JLabel();
        Problemas1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        msgrecu1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JLabel();
        fondoPrincipal1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondoabajo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new java.awt.BorderLayout());

        PanelMovible.setBorder(null);
        PanelMovible.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PanelMovible.setToolTipText("");
        PanelMovible.setPreferredSize(new java.awt.Dimension(1920, 2060));
        PanelMovible.setRequestFocusEnabled(false);

        panelBasico.setMinimumSize(new java.awt.Dimension(1920, 2060));
        panelBasico.setPreferredSize(new java.awt.Dimension(1920, 2010));
        panelBasico.setRequestFocusEnabled(false);
        panelBasico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtError.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 51, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelBasico.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 350, 590, 40));

        btnScrollDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Pestaña hacia abajoa.png"))); // NOI18N
        btnScrollDown.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnScrollDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnScrollDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScrollDownMouseClicked(evt);
            }
        });
        panelBasico.add(btnScrollDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 907, 420, 150));

        FitLogic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Logotipo FIT.png"))); // NOI18N
        panelBasico.add(FitLogic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 70));

        Problemas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/¿Problemas al iniciar sesión.png"))); // NOI18N
        panelBasico.add(Problemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setToolTipText("");
        txtCorreo.setBorder(null);
        txtCorreo.setDisabledTextColor(new java.awt.Color(235, 235, 235));
        txtCorreo.setOpaque(false);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        panelBasico.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 413, 585, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Campo Usuario.png"))); // NOI18N
        panelBasico.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        msgrecu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Se te enviará instrucciones a tu correo que registraste, con un código de verificación único, después de 6 horas el código quedará inválido..png"))); // NOI18N
        panelBasico.add(msgrecu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 660, 120));

        btnVolver.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Atrás btn.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        panelBasico.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 260, -1));

        btnEnviar.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Atrás btn-1.png"))); // NOI18N
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        panelBasico.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 260, -1));

        fondoPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/Fondo recuperar contraseña.png"))); // NOI18N
        panelBasico.add(fondoPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 930));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Group 106.png"))); // NOI18N
        panelBasico.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1140, 1810, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/Group 105.png"))); // NOI18N
        panelBasico.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1490, 1810, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuperar contraseña/FitLogic team.png"))); // NOI18N
        panelBasico.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 1950, 180, 50));

        fondoabajo.setBackground(new java.awt.Color(255, 255, 255));
        fondoabajo.setOpaque(true);
        panelBasico.add(fondoabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 930, 1920, 1080));

        PanelMovible.setViewportView(panelBasico);

        add(PanelMovible, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        FramePrincipal.Move(new Login());
    }//GEN-LAST:event_btnVolverMouseClicked
    //Enviar correo si existe, y comprobar si el código de recuperación de contraseña es válido
    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        if (codigoenviado == false){
            if ((!txtCorreo.getText().trim().isEmpty())){
                System.out.println("Hay texto");
                if (btnEnviar.isEnabled()){
                    System.out.println("Está habilitado");
                    if (ThirdLayer.BackEndUsuario.GetUsernameEmail(txtCorreo.getText())){
                        System.out.println("Existe el correo");
                        if (ThirdLayer.BackEndRecuperarContra.ThereIsARecoverPassSolicitude(
                                ThirdLayer.BackEndUsuario.getIdusuario())){
                            System.out.println("No hay una solicitud de contraseña reciente");
                            txtError.setText("");
                            if (ThirdLayer.Email.EnviarCorreo(txtCorreo.getText())){
                                correo = txtCorreo.getText();
                                codigoenviado = true;
                                btnScrollDown.setVisible(false);
                                PanelMovible.setPreferredSize(new java.awt.Dimension(1920, 1080));
                                panelBasico.setPreferredSize(new java.awt.Dimension(1920, 1080));
                                btnVolver.setVisible(false);
                                txtCorreo.setText("");
                                fondoPrincipal1.setIcon(
                                        new javax.swing.ImageIcon(
                                                getClass().
                                                        getResource("/Recuperar contraseña/Fondo main.png")
                                        )
                                );
                                Problemas1.setLocation(560, 140);
                                Problemas1.setIcon(
                                        new javax.swing.ImageIcon(
                                                getClass().
                                                        getResource("/Recuperar contraseña/Recupera tu cuentade FitLogic.png")
                                        )
                                );
                                msgrecu1.setIcon(new javax.swing.ImageIcon(
                                                getClass().
                                                        getResource("/Recuperar contraseña/codigomensajerecu.png")
                                        )
                                );
                                btnEnviar.setIcon(new javax.swing.ImageIcon(
                                                getClass().
                                                        getResource("/Recuperar contraseña/btn comprobar.png")
                                        )
                                );
                            } else txtError.setText("No se ha podido enviar el correo eléctronico.");
                        } else txtError.setText(
                                "<html><p style=\"text-align:center;\">Se ha solicitado un cambio de contraseña recientemente. "
                                        + "Intentalo de nuevo más tarde</p></html>"
                        );
                    } else txtError.setText("El correo ingresado no es valido.");
                }
            }
        } else {
            if ((!txtCorreo.getText().trim().isEmpty())){
                System.out.println("Hay texto");
                if (btnEnviar.isEnabled()){
                    System.out.println("Está habilitado");
                    if (ThirdLayer.BackEndRecuperarContra.getPin().equals(txtCorreo.getText())){
                        System.out.println("El código es válido.");
                        NewPassword.setPrimeravez(false);
                        FramePrincipal.Move(new NewPassword());
                    } else txtError.setText("<html><p style=\"text-align:center;\">El código ingresado es erronéo. "
                            + "Por favor inténtalo de nuevo.</p></html>");
                }
            }
        }
    }//GEN-LAST:event_btnEnviarMouseClicked
    //Moverse hacia abajo
    private void btnScrollDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScrollDownMouseClicked
        System.out.println("Click");
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                while (PanelMovible.getVerticalScrollBar().getValue() < 930){
                    PanelMovible.getVerticalScrollBar().setValue(PanelMovible.getVerticalScrollBar().getValue()+7);
                }
            }
        }, 0);
    }//GEN-LAST:event_btnScrollDownMouseClicked
    //Evento
    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        btnEnviar.setEnabled((!txtCorreo.getText().trim().isEmpty()));
    }//GEN-LAST:event_txtCorreoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FitLogic1;
    private javax.swing.JScrollPane PanelMovible;
    private javax.swing.JLabel Problemas1;
    private javax.swing.JLabel btnEnviar;
    private javax.swing.JLabel btnScrollDown;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel fondoPrincipal1;
    private javax.swing.JLabel fondoabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel msgrecu1;
    private javax.swing.JPanel panelBasico;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel txtError;
    // End of variables declaration//GEN-END:variables
}
