/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ThirdLayer.conexion;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author JosueLacayo
 */
public class Reportes extends javax.swing.JPanel {

    static void Move(OtrosFramePrincipal otrosFramePrincipal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnusuario = new javax.swing.JLabel();
        btnclases = new javax.swing.JLabel();
        btnusuarios = new javax.swing.JLabel();
        btnindumentaria = new javax.swing.JLabel();
        btnmembresia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/Tarjeta usuarios.png"))); // NOI18N
        btnusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnusuarioMousePressed(evt);
            }
        });
        add(btnusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 155));

        btnclases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/Tarjeta clases.png"))); // NOI18N
        btnclases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnclasesMousePressed(evt);
            }
        });
        add(btnclases, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, 151));

        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/Tarjeta usuarios.png"))); // NOI18N
        btnusuarios.setText("jLabel4");
        btnusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnusuariosMousePressed(evt);
            }
        });
        add(btnusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 426, -1));

        btnindumentaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/Tarjeta indumentaria.png"))); // NOI18N
        btnindumentaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnindumentariaMousePressed(evt);
            }
        });
        add(btnindumentaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, 155));

        btnmembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/Tarjeta membresías.png"))); // NOI18N
        btnmembresia.setText("jLabel4");
        btnmembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmembresiaMousePressed(evt);
            }
        });
        add(btnmembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 426, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/membresias icon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/clases icon.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 180, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/usuarios icon.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 180, 160));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/clases icon-1.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 470, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/tipo de usuario icon.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 230, 210, 160));
    }// </editor-fold>//GEN-END:initComponents
    //Método dinámico para mostrar reportes
    public static void ImprimirReporte(String path, Map parameters, String title){
        try{    
            JasperReport report = JasperCompileManager.compileReport(path);
            JasperPrint print = JasperFillManager.fillReport(report,parameters,conexion.Conectar());
            JasperViewer visor = new  JasperViewer(print,false);
            visor.setTitle(title);
            visor.setVisible(true);
        } catch (Exception ex) {
            System.out.println("Falló"+ ex.getMessage());
        }
    }
    
    private void btnmembresiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmembresiaMousePressed
        Map parametros = new HashMap();
        ImprimirReporte("reportes/ReporteMembresias.jrxml", parametros, "Reporte por membresías");
    }//GEN-LAST:event_btnmembresiaMousePressed

    private void btnusuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMousePressed
        Map parametros = new HashMap();
        ImprimirReporte("reportes/ReporteUsuarios.jrxml", parametros, "Reporte de usuarios");
    }//GEN-LAST:event_btnusuariosMousePressed

    private void btnusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuarioMousePressed
        Map parametros = new HashMap();
        ImprimirReporte("reportes/ReporteUsuarios.jrxml", parametros, "Reporte de usuarios");
    }//GEN-LAST:event_btnusuarioMousePressed

    private void btnclasesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclasesMousePressed
        Map parametros = new HashMap();
        ImprimirReporte("reportes/ReportesClases.jrxml", parametros, "Reporte Clases");
    }//GEN-LAST:event_btnclasesMousePressed

    private void btnindumentariaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnindumentariaMousePressed
        Map parametros = new HashMap();
        ImprimirReporte("reportes/ReporteIndumentaria.jrxml", parametros, "Reporte de Indumentaria");
    }//GEN-LAST:event_btnindumentariaMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnclases;
    private javax.swing.JLabel btnindumentaria;
    private javax.swing.JLabel btnmembresia;
    private javax.swing.JLabel btnusuario;
    private javax.swing.JLabel btnusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
