/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosueGalRe
 */
public class UsuarioSeeUsuario extends javax.swing.JPanel {

    //Asignamos variables
    DefaultTableModel modelo = new DefaultTableModel();
    String query1;
    String query2;
    
    int nivel = 0;
    /**
     * Creates new form SeeUser
     */
    public UsuarioSeeUsuario() {
        initComponents();
        modelo.addColumn("No.");
        modelo.addColumn("Nombres");
        modelo.addColumn("Nivel");
        modelo.addColumn("Estado");
        Tabla.setModel(modelo);
        //Dependiendo del tipo de usuario, se muestran los datos en pantalla
        switch(ThirdLayer.BackEndUsuario.getIdtipousuario()){
            default:
                query2 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
                + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
                + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado "
                + "AND (u.nombres+' '+u.apellidos) LIKE ? ";
                query1 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
                + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
                + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado";
                break;
            case 3:
                query2 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
                + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
                + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado "
                + "AND (u.nombres+' '+u.apellidos) LIKE ? AND t.idtipousuario = 5";
                query1 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
                + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
                + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado AND t.idtipousuario = 5";
                btnAdmin.setVisible(false);
                btnCouces.setVisible(false);
                btnGerentes.setVisible(false);
                btnRecepcionistas.setVisible(false);
                btnClientes.setIcon(
                       new javax.swing.ImageIcon(
                                getClass().getResource(
                                        "/GUI FitLogic/VIsualizar usuarios/Clientes.png")
                        )
                );
                break;
        }
        RecargarTabla(Tabla, modelo, query1);
        FillLabels();
    }
    //Rellenar los labels informativos con la cantidad de usuarios
    private void FillLabels(){
        String query = "SELECT COUNT(Usuario) FROM Usuario WHERE idtipousuario = ?";
        numeroAdmin.setText(String.valueOf(ThirdLayer.BackEnd.getExecuteInt(query, 1)));
        numeroGerentes.setText(String.valueOf(ThirdLayer.BackEnd.getExecuteInt(query, 2)));
        numeroRecep.setText(String.valueOf(ThirdLayer.BackEnd.getExecuteInt(query, 3)));
        numeroCouches.setText(String.valueOf(ThirdLayer.BackEnd.getExecuteInt(query, 4)));
        numeroClientes.setText(String.valueOf(ThirdLayer.BackEnd.getExecuteInt(query, 5)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerentes = new javax.swing.JLabel();
        btnRecepcionistas = new javax.swing.JLabel();
        btnCouces = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        numeroGerentes = new javax.swing.JLabel();
        numeroRecep = new javax.swing.JLabel();
        numeroCouches = new javax.swing.JLabel();
        numeroClientes = new javax.swing.JLabel();
        numeroAdmin = new javax.swing.JLabel();
        lblGerentes = new javax.swing.JLabel();
        lblRecepcionistas = new javax.swing.JLabel();
        lblCouches = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblAdministradores = new javax.swing.JLabel();
        textoflitros2 = new javax.swing.JLabel();
        barrafiltros = new javax.swing.JLabel();
        textoflitros = new javax.swing.JLabel();
        barrabuscar = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1467, 1480));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerentesMouseClicked(evt);
            }
        });
        add(btnGerentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 210, 60));

        btnRecepcionistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecepcionistasMouseClicked(evt);
            }
        });
        add(btnRecepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 200, 60));

        btnCouces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCoucesMouseClicked(evt);
            }
        });
        add(btnCouces, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 200, 60));

        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 150, 200, 60));

        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
        });
        add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 210, 60));

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 730, 40));

        numeroGerentes.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        numeroGerentes.setForeground(new java.awt.Color(0, 0, 0));
        numeroGerentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(numeroGerentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 160, 70));

        numeroRecep.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        numeroRecep.setForeground(new java.awt.Color(0, 0, 0));
        numeroRecep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(numeroRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 160, 70));

        numeroCouches.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        numeroCouches.setForeground(new java.awt.Color(0, 0, 0));
        numeroCouches.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(numeroCouches, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 160, 70));

        numeroClientes.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        numeroClientes.setForeground(new java.awt.Color(0, 0, 0));
        numeroClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(numeroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 290, 160, 70));

        numeroAdmin.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        numeroAdmin.setForeground(new java.awt.Color(0, 0, 0));
        numeroAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(numeroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, 70));

        lblGerentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra Gerentes.png"))); // NOI18N
        add(lblGerentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        lblRecepcionistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra Recepcionistas.png"))); // NOI18N
        add(lblRecepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        lblCouches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra Couches.png"))); // NOI18N
        add(lblCouches, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, -1, -1));

        lblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra Clientes.png"))); // NOI18N
        add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 370, -1, -1));

        lblAdministradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra Administradores.png"))); // NOI18N
        add(lblAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        textoflitros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Rectangulo infromante.png"))); // NOI18N
        add(textoflitros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 1300, 160));

        barrafiltros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra de filtros.png"))); // NOI18N
        add(barrafiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 60));

        textoflitros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Filtros.png"))); // NOI18N
        add(textoflitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, 60));

        barrabuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra de búsqueda.png"))); // NOI18N
        add(barrabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 1140, 80));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Botón buscar.png"))); // NOI18N
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 200, 60));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        Tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabla.setShowVerticalLines(false);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 1300, 1050));

        lblError.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setToolTipText("");
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 330, 20));
    }// </editor-fold>//GEN-END:initComponents
    //Recargar una tabla con una query específica
    private void RecargarTablaEspecifica(){
        try {
            modelo.setRowCount(0);
            String query = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
                    + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
                    + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado AND t.idtipousuario = ?";
            ThirdLayer.BackEnd.FillTablaEspecifico(Tabla, query, nivel);
            System.out.println("Funciona la query");
        } catch (Exception e) {System.out.println("Fallo la query: "+e.getMessage());}
    }
    //Recargar una tabla general
    public static void RecargarTabla(javax.swing.JTable Tabla, DefaultTableModel modelo, String query){
        try {
            modelo.setRowCount(0);
            ThirdLayer.BackEnd.FillTablaGeneral(Tabla, query);
            System.out.println("Funciona la query");
        } catch (Exception e) {System.out.println("Fallo la query");}
    }
    //Recargar una tabla pero buscando
    public static String RecargarTablaBusqueda(javax.swing.JTable Tabla, String busqueda, DefaultTableModel modelo, String query){
        String lblError = "";
        try {
            if (!busqueda.trim().isEmpty()){
                lblError = "";
                modelo.setRowCount(0);
                ThirdLayer.BackEnd.FillTablaEspecifico(Tabla, query, "%"+busqueda+"%");
                System.out.println("Funciona la query");
            } else lblError = "Por favor ingresa el criterio de búsqueda";
        } catch (Exception e) {System.out.println("Fallo la query");}
        return lblError;
    }
    //Eventos
    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        nivel = 1;
        btnAdmin.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource(
                                "/GUI FitLogic/VIsualizar usuarios/Admin.png")
                )
        );
        btnGerentes.setIcon(null);
        btnRecepcionistas.setIcon(null);
        btnCouces.setIcon(null);
        btnClientes.setIcon(null);
        FillLabels();
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnAdminMouseClicked

    private void btnGerentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerentesMouseClicked
        nivel = 2;
        btnGerentes.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource(
                                "/GUI FitLogic/VIsualizar usuarios/Gerentes.png")
                )
        );
        btnAdmin.setIcon(null);
        btnRecepcionistas.setIcon(null);
        btnCouces.setIcon(null);
        btnClientes.setIcon(null);
        FillLabels();
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnGerentesMouseClicked

    private void btnRecepcionistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionistasMouseClicked
        nivel = 3;
        btnRecepcionistas.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource(
                                "/GUI FitLogic/VIsualizar usuarios/Recepcionistas.png")
                )
        );
        btnGerentes.setIcon(null);
        btnAdmin.setIcon(null);
        btnCouces.setIcon(null);
        btnClientes.setIcon(null);
        FillLabels();
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnRecepcionistasMouseClicked

    private void btnCoucesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoucesMouseClicked
        nivel = 4;
        btnCouces.setIcon(
                new javax.swing.ImageIcon(
                        getClass().getResource(
                                "/GUI FitLogic/VIsualizar usuarios/Couches.png")
                )
        );
        btnGerentes.setIcon(null);
        btnRecepcionistas.setIcon(null);
        btnAdmin.setIcon(null);
        btnClientes.setIcon(null);
        FillLabels();
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnCoucesMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        nivel = 5;
        btnClientes.setIcon(
               new javax.swing.ImageIcon(
                        getClass().getResource(
                                "/GUI FitLogic/VIsualizar usuarios/Clientes.png")
                )
        );
        btnGerentes.setIcon(null);
        btnRecepcionistas.setIcon(null);
        btnCouces.setIcon(null);
        btnAdmin.setIcon(null);
        FillLabels();
        RecargarTablaEspecifica();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        nivel = 0;
        switch(ThirdLayer.BackEndUsuario.getIdtipousuario()){
            default:
                btnAdmin.setIcon(null);
                btnGerentes.setIcon(null);
                btnRecepcionistas.setIcon(null);
                btnCouces.setIcon(null);
                btnClientes.setIcon(null);
                FillLabels();
                break;
            case 3: break;
        }
        RecargarTabla(Tabla, modelo, query1);
    }//GEN-LAST:event_formMouseClicked
    //Bóton buscar
    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
    }//GEN-LAST:event_btnbuscarMouseClicked
    //Validación de texto
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_ENTER){
            UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
            FillLabels();
        }
        if (txtBuscar.getText().trim().length() <= 1 || txtBuscar.getText().trim().isEmpty()){
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
            FillLabels();
        }
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel barrabuscar;
    private javax.swing.JLabel barrafiltros;
    private javax.swing.JLabel btnAdmin;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnCouces;
    private javax.swing.JLabel btnGerentes;
    private javax.swing.JLabel btnRecepcionistas;
    private javax.swing.JLabel btnbuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdministradores;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCouches;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGerentes;
    private javax.swing.JLabel lblRecepcionistas;
    private javax.swing.JLabel numeroAdmin;
    private javax.swing.JLabel numeroClientes;
    private javax.swing.JLabel numeroCouches;
    private javax.swing.JLabel numeroGerentes;
    private javax.swing.JLabel numeroRecep;
    private javax.swing.JLabel textoflitros;
    private javax.swing.JLabel textoflitros2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
