/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosueGalRe
 */
public class UsuarioEditUsuario extends javax.swing.JPanel {
    
    //Declaración de variables
    DefaultTableModel modelo = new DefaultTableModel();
    
    int membresia = 0;
    int nivel = 0;
    char genero = 'G';
    int estadou = 0;
    
    int modoeditar = 0;
    
    String query1;
    String query2;

    /**
     * Creates new form EditUser
     */
    public UsuarioEditUsuario() {
        initComponents();
        //Placeholders de los campos de texto
        new ThirdLayer.PTextField.GhostText(txtNombres, "Nombres");
        new ThirdLayer.PTextField.GhostText(txtApellidos, "Apellidos");
        new ThirdLayer.PTextField.GhostText(txtEmail, "Correo Eléctronico");
        new ThirdLayer.PTextField.GhostText(txtUsuario, "Usuario");
        new ThirdLayer.PTextField.GhostText(txtPeso, "Peso");
        new ThirdLayer.PTextField.GhostText(txtDireccion, "Dirección");
        new ThirdLayer.PTextField.GhostText(txtAltura, "Altura");
        
        modelo.addColumn("No.");
        modelo.addColumn("Nombres");
        modelo.addColumn("Nivel");
        modelo.addColumn("Estado");
        Tabla.setModel(modelo);
        query2 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
        + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
        + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado "
        + "AND (u.nombres+' '+u.apellidos) LIKE ? AND idusuario != "+ThirdLayer.BackEndUsuario.getIdusuario();
        query1 = "SELECT u.idusuario, (u.nombres+' '+u.apellidos), t.tipo, e.estado "
        + "FROM TipoUsuario t, Usuario u, EstadoUsuario e "
        + "WHERE t.idtipousuario = u.idtipousuario AND e.idestado = u.idestado AND idusuario != "
                +ThirdLayer.BackEndUsuario.getIdusuario();
        UsuarioSeeUsuario.RecargarTabla(Tabla, modelo,query1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DUI1 = new javax.swing.JLabel();
        DUI = new javax.swing.JLabel();
        infofecha = new javax.swing.JLabel();
        btnPremium = new javax.swing.JLabel();
        btnEstandar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnActivo = new javax.swing.JLabel();
        btnInactivo = new javax.swing.JLabel();
        btnCouch = new javax.swing.JLabel();
        btnRecepcionista = new javax.swing.JLabel();
        btnAdministrador = new javax.swing.JLabel();
        btnGerente = new javax.swing.JLabel();
        btnCliente = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        Hombre = new javax.swing.JLabel();
        Mujer = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtDUI = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        txtAltura = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        sombrapremium = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        barrabuscar = new javax.swing.JLabel();
        sombraestandar = new javax.swing.JLabel();
        lblUsuarioSeleccioando = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        barrabuscar1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnCliente1 = new javax.swing.JLabel();
        btnGerente1 = new javax.swing.JLabel();
        btnCouch1 = new javax.swing.JLabel();
        btnRecepcionista1 = new javax.swing.JLabel();
        btnAdministrador1 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(1467, 1960));
        setPreferredSize(new java.awt.Dimension(1947, 1947));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DUI1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DUI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DUI1.setText("Télefono");
        add(DUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 1320, 110, -1));

        DUI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DUI.setText("DUI (completo)");
        add(DUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1535, 110, -1));

        infofecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infofecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infofecha.setText("YYYY/mm/DD");
        add(infofecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1320, 100, -1));

        btnPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Membresía premium.png"))); // NOI18N
        btnPremium.setEnabled(false);
        btnPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPremiumMouseClicked(evt);
            }
        });
        add(btnPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1710, 320, 170));

        btnEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Membresía estándar.png"))); // NOI18N
        btnEstandar.setEnabled(false);
        btnEstandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstandarMouseClicked(evt);
            }
        });
        add(btnEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1710, 330, 170));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setEnabled(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 1770, -1, 40));

        btnActivo.setEnabled(false);
        btnActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivoMouseClicked(evt);
            }
        });
        add(btnActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1820, 130, 40));

        btnInactivo.setEnabled(false);
        btnInactivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInactivoMouseClicked(evt);
            }
        });
        add(btnInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1820, 130, 40));

        btnCouch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Tarjeta coach.png"))); // NOI18N
        btnCouch.setEnabled(false);
        btnCouch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCouchMouseClicked(evt);
            }
        });
        add(btnCouch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1570, 300, 100));

        btnRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Tarjeta recepcionista.png"))); // NOI18N
        btnRecepcionista.setEnabled(false);
        btnRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecepcionistaMouseClicked(evt);
            }
        });
        add(btnRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1570, 300, 100));

        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Tarjeta administrador.png"))); // NOI18N
        btnAdministrador.setEnabled(false);
        btnAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdministradorMouseClicked(evt);
            }
        });
        add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 1570, 300, 100));

        btnGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Tarjeta gerente.png"))); // NOI18N
        btnGerente.setEnabled(false);
        btnGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGerenteMouseClicked(evt);
            }
        });
        add(btnGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1710, 300, 100));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Tarjeta Cliente.png"))); // NOI18N
        btnCliente.setEnabled(false);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
        });
        add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1570, 300, 100));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Botón actualizar.png"))); // NOI18N
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setEnabled(false);
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1880, 300, 100));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Botón buscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, 200, 60));

        Hombre.setToolTipText("");
        Hombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HombreMouseClicked(evt);
            }
        });
        add(Hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1470, 130, 70));

        Mujer.setToolTipText("");
        Mujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MujerMouseClicked(evt);
            }
        });
        add(Mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 1470, 140, 70));

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setToolTipText("");
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1900, 1040, 50));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBorder(null);
        txtUsuario.setEnabled(false);
        txtUsuario.setOpaque(false);
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1160, 480, 50));

        txtDUI.setBorder(null);
        try {
            txtDUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDUI.setToolTipText("");
        txtDUI.setEnabled(false);
        txtDUI.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtDUI.setOpaque(false);
        add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1477, 550, 50));

        txtTelefono.setBorder(null);
        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setToolTipText("");
        txtTelefono.setEnabled(false);
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtTelefono.setOpaque(false);
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1263, 430, 50));

        txtFecha.setBorder(null);
        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setToolTipText("");
        txtFecha.setEnabled(false);
        txtFecha.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtFecha.setOpaque(false);
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1263, 290, 50));

        txtAltura.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtAltura.setForeground(new java.awt.Color(0, 0, 0));
        txtAltura.setBorder(null);
        txtAltura.setEnabled(false);
        txtAltura.setOpaque(false);
        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1263, 140, 50));

        txtPeso.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 0, 0));
        txtPeso.setBorder(null);
        txtPeso.setEnabled(false);
        txtPeso.setOpaque(false);
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1263, 140, 50));

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setBorder(null);
        txtDireccion.setEnabled(false);
        txtDireccion.setOpaque(false);
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1372, 1170, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(null);
        txtEmail.setEnabled(false);
        txtEmail.setOpaque(false);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1160, 640, 50));

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setBorder(null);
        txtApellidos.setEnabled(false);
        txtApellidos.setOpaque(false);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 1053, 550, 50));

        txtNombres.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setBorder(null);
        txtNombres.setEnabled(false);
        txtNombres.setOpaque(false);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1053, 550, 50));

        txtBuscar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);
        txtBuscar.setOpaque(false);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 730, 40));

        lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra hombre.png"))); // NOI18N
        lblGenero.setEnabled(false);
        add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 1470, -1, -1));

        sombrapremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Sombra membresía premium.png"))); // NOI18N
        sombrapremium.setEnabled(false);
        add(sombrapremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 1660, -1, 270));

        estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Barra activo-inactivo.png"))); // NOI18N
        estado.setEnabled(false);
        add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1820, 270, 50));

        barrabuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Campos.png"))); // NOI18N
        barrabuscar.setEnabled(false);
        add(barrabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1040, 1220, 500));

        sombraestandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Sombra membresía estándar.png"))); // NOI18N
        add(sombraestandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1660, -1, 270));

        lblUsuarioSeleccioando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios - editar seleccionado/Usuario seleccionado.png"))); // NOI18N
        lblUsuarioSeleccioando.setEnabled(false);
        add(lblUsuarioSeleccioando, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 980, 850, 60));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios/Busca un usuario para editar..png"))); // NOI18N
        add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 850, 60));

        barrabuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/VIsualizar usuarios/Barra de búsqueda.png"))); // NOI18N
        add(barrabuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1140, 80));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios/Botón buscar-1.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 730, -1, 60));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI FitLogic/Editar usuarios/Botón buscar.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 850, -1, 60));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(153, 153, 153));
        Tabla.setRowHeight(64);
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 1090, 660));

        btnCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Sombra gerente.png"))); // NOI18N
        btnCliente1.setEnabled(false);
        add(btnCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1670, -1, -1));

        btnGerente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Sombra gerente.png"))); // NOI18N
        btnGerente1.setEnabled(false);
        add(btnGerente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1530, -1, -1));

        btnCouch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Sombra gerente.png"))); // NOI18N
        btnCouch1.setEnabled(false);
        add(btnCouch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1530, -1, -1));

        btnRecepcionista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Sombra gerente.png"))); // NOI18N
        btnRecepcionista1.setEnabled(false);
        add(btnRecepcionista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 1530, -1, -1));

        btnAdministrador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Sombra administrador.png"))); // NOI18N
        btnAdministrador1.setEnabled(false);
        add(btnAdministrador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 1530, -1, -1));

        lblError1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError1.setForeground(new java.awt.Color(255, 0, 51));
        lblError1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError1.setToolTipText("");
        add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 550, 200, 120));
    }// </editor-fold>//GEN-END:initComponents
    //Limpiar campos en pantalla
    private void LimpiarCampos(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtEmail.setText("");
        txtDireccion.setText("");
        txtPeso.setText(String.valueOf(""));
        txtAltura.setText(String.valueOf(""));
        txtDUI.setText("");
        txtTelefono.setText("");
        txtFecha.setText("");
        txtUsuario.setText("");
    }
    //Cambiar el estado de los componentes
    private void cambiarEstado(boolean value){
        //Componentes pintados
        lblUsuarioSeleccioando.setEnabled(value);
        barrabuscar.setEnabled(value);
        estado.setEnabled(value);
        lblGenero.setEnabled(value);
        //Campos de texto
        txtNombres.setEnabled(value);
        txtApellidos.setEnabled(value);
        txtEmail.setEnabled(value);
        txtDireccion.setEnabled(value);
        if (value == false && nivel < 6) {
            txtPeso.setEnabled(false);
            txtAltura.setEnabled(false);
            btnEstandar.setEnabled(false);
            btnPremium.setEnabled(false);
        } else if (value == true && nivel == 5){
            txtPeso.setEnabled(true);
            txtAltura.setEnabled(true);
            btnEstandar.setEnabled(true);
            btnPremium.setEnabled(true);
        }
        txtDUI.setEnabled(value);
        txtTelefono.setEnabled(value);
        txtFecha.setEnabled(value);
        txtUsuario.setEnabled(value);
        //Botones
        btnCliente.setEnabled(value);
        btnGerente.setEnabled(value);
        btnRecepcionista.setEnabled(value);
        btnCouch.setEnabled(value);
        btnAdministrador.setEnabled(value);
        btnActivo.setEnabled(value);
        btnInactivo.setEnabled(value);
        btnActualizar.setEnabled(value);
        btnCancelar.setEnabled(value);
        Mujer.setEnabled(value);
        Hombre.setEnabled(value);
    }
    //Regresar hacia arriba
    private void Regresar(){
        if(modoeditar == 1) {
            UsuarioFormularioPrincipal.SeeUserMove1();
            LimpiarCampos();
            cambiarEstado(false);
            modoeditar = 0;
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        }
    }
    //Editar el usuario seleccionado
    private void Editar(){
        if (Tabla.getSelectedRow() != -1){
            lblError1.setText("");
            modoeditar = 1;
            ThirdLayer.BackEndUsuarioCliente.GetUserInformation((Integer) Tabla.getValueAt(Tabla.getSelectedRow(), 0));
            //Asignando valores
            txtNombres.setText(ThirdLayer.BackEndUsuarioCliente.getNombres());
            txtApellidos.setText(ThirdLayer.BackEndUsuarioCliente.getApellidos());
            txtEmail.setText(ThirdLayer.BackEndUsuarioCliente.getEmail());
            txtDireccion.setText(ThirdLayer.BackEndUsuarioCliente.getDireccion());
            txtDUI.setText(ThirdLayer.BackEndUsuarioCliente.getDui());
            txtTelefono.setText(ThirdLayer.BackEndUsuarioCliente.getTelefono());
            txtFecha.setText(ThirdLayer.BackEndUsuarioCliente.getNacimiento());
            txtUsuario.setText(ThirdLayer.BackEndUsuarioCliente.getUsuario());
            nivel = ThirdLayer.BackEndUsuarioCliente.getIdtipousuario();
            if (nivel == 5){
                txtPeso.setText(String.valueOf(ThirdLayer.BackEndUsuarioCliente.getPeso()));
                txtAltura.setText(String.valueOf(ThirdLayer.BackEndUsuarioCliente.getAltura()));
                membresia = ThirdLayer.BackEndUsuarioCliente.getIdmembresia();
            }
            genero = ThirdLayer.BackEndUsuarioCliente.getGenero();
            estadou = ThirdLayer.BackEndUsuarioCliente.getIdestado();
            System.out.println(ThirdLayer.BackEndUsuarioCliente.getIdmembresia());
            System.out.println(membresia);
            cambiarEstado(true);
            switch (membresia){
                case 1:{
                    btnPremium.setEnabled(false);
                    break;}
                case 2:{
                    btnEstandar.setEnabled(false);
                    break;}
            }
            System.out.println(nivel);
            switch (nivel){
                case 1: {
                    btnAdministrador.setEnabled(false);
                    break;
                }
                case 2:{
                    btnGerente.setEnabled(false);
                    break;
                }
                case 3:{
                    btnRecepcionista.setEnabled(false);
                    break;
                }
                case 4:{
                    btnCouch.setEnabled(false);
                    break;
                }
                case 5:{
                    btnCliente.setEnabled(false);
                    break;
                }
            }
            System.out.println(genero);
            switch (genero){
                case 'M':
                    lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra hombre.png")));
                    break;
                case 'F':
                    lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra mujer.png")));
                    break;
            }
            System.out.println(estadou);
            switch (estadou){
                case 1:
                    estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra activo.png")));
                    break;
                case 2:
                    estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra inactivo.png")));
                    break;
            }
            UsuarioFormularioPrincipal.AddUserMover1();
        } else lblError1.setText(
            "<html><p style=\"style-align:center;\">Por favor seleccione un usuario para modificar.</p></html>");
    }
    //Eventos
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if (modoeditar == 1)
            Regresar();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        if (modoeditar == 1)
            Actualizar();
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Editar();
    }//GEN-LAST:event_btnEditarMouseClicked
    //Validación de texto
    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_ENTER)
            UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
        if (txtBuscar.getText().trim().length() <= 1 || txtBuscar.getText().trim().isEmpty())
            UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
        if (!(Character.isAlphabetic(c) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_BACK_SPACE))
            evt.consume();
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        UsuarioSeeUsuario.RecargarTablaBusqueda(Tabla, txtBuscar.getText(), modelo, query2);
    }//GEN-LAST:event_btnBuscarMouseClicked
    //Eliminar usuario
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (Tabla.getSelectedRow() != -1){
            System.out.println(ThirdLayer.BackEndUsuarioCliente.getIdusuario());
            if (JOptionPane.showConfirmDialog(
                    null, 
                    "¿Desea eliminar al usuario seleccionado?", 
                    "Advertencia", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) 
                    == JOptionPane.YES_OPTION){
            if (ThirdLayer.BackEndUsuarioCliente.EliminarUsuario()){
                UsuarioSeeUsuario.RecargarTabla(Tabla, modelo, query1);
            } else JOptionPane.showMessageDialog(null, "No se ha podido eliminar el usuario.", "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked
    //Eventos
    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        if (modoeditar == 1){
            nivel = 5;
            txtPeso.setEnabled(true);
            txtAltura.setEnabled(true);
            btnPremium.setEnabled(true);
            btnEstandar.setEnabled(true);
            btnCouch.setEnabled(true);
            btnRecepcionista.setEnabled(true);
            btnAdministrador.setEnabled(true);
            btnGerente.setEnabled(true);
            btnCliente.setEnabled(false);
        }
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnCouchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCouchMouseClicked
        if (modoeditar == 1){
            nivel = 4;
            txtPeso.setEnabled(false);
            txtAltura.setEnabled(false);
            btnPremium.setEnabled(false);
            btnEstandar.setEnabled(false);
            btnCouch.setEnabled(false);
            btnRecepcionista.setEnabled(true);
            btnAdministrador.setEnabled(true);
            btnGerente.setEnabled(true);
            btnCliente.setEnabled(true);
        }
    }//GEN-LAST:event_btnCouchMouseClicked

    private void btnRecepcionistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecepcionistaMouseClicked
        if (modoeditar == 1){
            nivel = 3;
            txtPeso.setEnabled(false);
            txtAltura.setEnabled(false);
            btnPremium.setEnabled(false);
            btnEstandar.setEnabled(false);
            btnCouch.setEnabled(true);
            btnRecepcionista.setEnabled(false);
            btnAdministrador.setEnabled(true);
            btnGerente.setEnabled(true);
            btnCliente.setEnabled(true);
        }
    }//GEN-LAST:event_btnRecepcionistaMouseClicked

    private void btnAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministradorMouseClicked
        if (modoeditar == 1){
            nivel = 1;
            txtPeso.setEnabled(false);
            txtAltura.setEnabled(false);
            btnPremium.setEnabled(false);
            btnEstandar.setEnabled(false);
            btnCouch.setEnabled(true);
            btnRecepcionista.setEnabled(true);
            btnAdministrador.setEnabled(false);
            btnGerente.setEnabled(true);
            btnCliente.setEnabled(true);
        }
    }//GEN-LAST:event_btnAdministradorMouseClicked

    private void btnGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenteMouseClicked
        if (modoeditar == 1){
            nivel = 2;
            txtPeso.setEnabled(false);
            txtAltura.setEnabled(false);
            btnPremium.setEnabled(false);
            btnEstandar.setEnabled(false);
            btnCouch.setEnabled(true);
            btnRecepcionista.setEnabled(true);
            btnAdministrador.setEnabled(true);
            btnGerente.setEnabled(false);
            btnCliente.setEnabled(true);
        }
    }//GEN-LAST:event_btnGerenteMouseClicked

    private void HombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HombreMouseClicked
        if (modoeditar == 1){
            genero = 'M';
            lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra hombre.png")));
        }
    }//GEN-LAST:event_HombreMouseClicked

    private void MujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MujerMouseClicked
        if (modoeditar == 1){
            genero = 'F';
            lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra mujer.png")));
        }
    }//GEN-LAST:event_MujerMouseClicked

    private void btnActivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivoMouseClicked
        if (modoeditar == 1){
            estadou = 1;
            estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra activo.png")));
        }
    }//GEN-LAST:event_btnActivoMouseClicked

    private void btnInactivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInactivoMouseClicked
        if (modoeditar == 1){
            estadou = 2;
            estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar usuario/Barra inactivo.png")));
        }
    }//GEN-LAST:event_btnInactivoMouseClicked

    private void btnEstandarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstandarMouseClicked
        if (modoeditar == 1 && btnEstandar.isEnabled() == true){
            membresia = 1;
            btnEstandar.setEnabled(false);
            btnPremium.setEnabled(true);
        }
    }//GEN-LAST:event_btnEstandarMouseClicked

    private void btnPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPremiumMouseClicked
        if (modoeditar == 1 && btnPremium.isEnabled() == true){
            membresia = 2;
            btnEstandar.setEnabled(true);
            btnPremium.setEnabled(false);
        }
    }//GEN-LAST:event_btnPremiumMouseClicked
    //Validaciones de texto
    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) ||  (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_SPACE || c == KeyEvent.VK_QUOTE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombresKeyTyped
    //Método para actualizar un usuario
    private void Actualizar(){
        int cliente = 0;
        String [] dui = txtDUI.getText().split("-", 2);
        String [] fecha = txtFecha.getText().split("-", 3);
        String [] telefono = txtTelefono.getText().split("-", 2);
        
        String STelefono = new StringBuilder().append(telefono[0]).append(telefono[1]).toString().trim();
        String SFecha = new StringBuilder().append(fecha[0]).append(fecha[1]).append(fecha[2]).toString().trim();
        String SDui = new StringBuilder().append(dui[0]).append(dui[1]).toString().trim();
        System.out.println(
                "N: "+ txtNombres.getText() +" A: "+ txtApellidos.getText() +
                " E: "+ txtEmail.getText() +" D: "+ 
                SDui +" F: "+ SFecha +" T: "+ STelefono 
                +" G: "+ genero +" E: "+ estadou +" Dr: "+ txtDireccion.getText() +" U: "+ txtUsuario.getText()+" N: " + nivel);
        if (!txtNombres.getText().trim().isEmpty() && !txtApellidos.getText().trim().isEmpty() &&
            !txtEmail.getText().trim().isEmpty() && !SDui.trim().isEmpty() &&
            !SFecha.trim().isEmpty() && !STelefono.trim().isEmpty() &&
            genero != 'G' && estadou > 0 &&
            !txtDireccion.getText().trim().isEmpty() && nivel != 0 &&
            !txtUsuario.getText().trim().isEmpty()){
            if (
                    (nivel != 5) 
                    || 
                    (nivel == 5 && 
                        (
                            !txtPeso.getText().trim().isEmpty() || !txtPeso.getText().equalsIgnoreCase("0.0")) 
                        && (
                            !txtAltura.getText().trim().isEmpty() || !txtAltura.getText().equalsIgnoreCase("0.0")
                        )
                    )
                ){
                Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
                Matcher mather = pattern.matcher(txtEmail.getText());

                if (mather.find() == true) {
                    String[] fechan = txtFecha.getText().split("-");
                    Integer[] fechas = new Integer[fechan.length];
                    
                    int i = 0;
                    for(String f: fechan){
                        fechas[i]=Integer.parseInt(f);
                        i++;}
                    
                    if ((fechas[0] <= 2001 && fechas[1] <= 12) &&
                        ((fechas[1] == 1 && fechas[2] <= 31) ||
                        (fechas[1] == 2 && fechas[2] <= 29) ||
                        (fechas[1] == 3 && fechas[2] <= 31) ||
                        (fechas[1] == 4 && fechas[2] <= 30) ||
                        (fechas[1] == 5 && fechas[2] <= 31) ||
                        (fechas[1] == 6 && fechas[2] <= 30) ||
                        (fechas[1] == 7 && fechas[2] <= 31) ||
                        (fechas[1] == 8 && fechas[2] <= 31) ||
                        (fechas[1] == 9 && fechas[2] <= 30) ||
                        (fechas[1] == 10 && fechas[2] <= 31) ||
                        (fechas[1] == 11 && fechas[2] <= 30) ||
                        (fechas[1] == 12 && fechas[2] <= 31))){
                        boolean a = ThirdLayer.BackEndUsuarioCliente.GetExistingDUIid(txtDUI.getText()) == 
                                ThirdLayer.BackEndUsuarioCliente.getIdcliente();
                        System.out.println(ThirdLayer.BackEndUsuarioCliente.getIdcliente());
                        System.out.println(a);
                        if (ThirdLayer.BackEndUsuarioCliente.GetExistingDUI(txtDUI.getText()) == false || 
                                ThirdLayer.BackEndUsuarioCliente.GetExistingDUIid(txtDUI.getText()) == 
                                ThirdLayer.BackEndUsuarioCliente.getIdusuario()){
                            ThirdLayer.BackEndUsuarioCliente.setNombres(txtNombres.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setApellidos(txtApellidos.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setUsuario(txtUsuario.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setEmail(txtEmail.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setDui(txtDUI.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setNacimiento(txtFecha.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setDireccion(txtDireccion.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setTelefono(txtTelefono.getText().trim());
                            ThirdLayer.BackEndUsuarioCliente.setGenero(genero);
                            ThirdLayer.BackEndUsuarioCliente.setIdestado(estadou);
                            ThirdLayer.BackEndUsuarioCliente.setIdtipousuario(nivel);
                            if (nivel == 5){
                                ThirdLayer.BackEndUsuarioCliente.setPeso(Double.valueOf(txtPeso.getText().trim()));
                                ThirdLayer.BackEndUsuarioCliente.setPeso(Double.valueOf(txtAltura.getText().trim()));
                                ThirdLayer.BackEndUsuarioCliente.setIdmembresia(membresia);
                                cliente = 1;
                            }
                            if (cliente == 0){
                                if (ThirdLayer.BackEndUsuarioCliente.ActualizarUsuario())
                                    Regresar();
                                else lblError.setText(
                                "<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                                    + " por favor verifique los datos otra vez.</p></html>"
                            );} else {
                                if (ThirdLayer.BackEndUsuarioCliente.ActualizarCliente())
                                    Regresar();
                                else lblError.setText(
                                "<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                                    + " por favor verifique los datos otra vez.</p></html>"
                            );}
                        } else lblError.setText(
                            "<html><p style=\"style-align:center;\">El dui ingresado ya existe en nuestros registros, "
                                + "por favor verifíque si es correcto.</p></html>"
                    );} else lblError.setText(
                        "<html><p style=\"style-align:center;\">La fecha ingresada no es correcta.</p></html>"
                );} else lblError.setText(
                    "<html><p style=\"style-align:center;\">Por favor rellene el correo eléctronico para continuar.</p></html>"
            );} else lblError.setText(
                "<html><p style=\"style-align:center;\">Por favor rellene todos los campos de cliente para continuar.</p></html>"
        );} else lblError.setText(
            "<html><p style=\"style-align:center;\">Por favor rellene todos los campos de usuario para continuar. </p></html>"
    );}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DUI;
    private javax.swing.JLabel DUI1;
    private javax.swing.JLabel Hombre;
    private javax.swing.JLabel Mujer;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel barrabuscar;
    private javax.swing.JLabel barrabuscar1;
    private javax.swing.JLabel btnActivo;
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnAdministrador;
    private javax.swing.JLabel btnAdministrador1;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCliente;
    private javax.swing.JLabel btnCliente1;
    private javax.swing.JLabel btnCouch;
    private javax.swing.JLabel btnCouch1;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnEstandar;
    private javax.swing.JLabel btnGerente;
    private javax.swing.JLabel btnGerente1;
    private javax.swing.JLabel btnInactivo;
    private javax.swing.JLabel btnPremium;
    private javax.swing.JLabel btnRecepcionista;
    private javax.swing.JLabel btnRecepcionista1;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel infofecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblUsuarioSeleccioando;
    private javax.swing.JLabel sombraestandar;
    private javax.swing.JLabel sombrapremium;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtDUI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
