/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author JosueGalRe
 */
public class UsuarioAddCliente extends javax.swing.JPanel {

    //Declaración de variables
    private static int nivel = 0;
    
    static int membresia = 0;
    
    static char genero = 'G';
    
    /**
     * Creates new form cliente
     */
    public UsuarioAddCliente() {
        initComponents();
        //Información en pantalla según el nivel de usuario
        switch (ThirdLayer.BackEndUsuario.getIdtipousuario()){
            case 1:
                break;
            case 2:
                break;
            case 3:
                Coach.setVisible(false);
                Recepcionista.setVisible(false);
                Gerente.setVisible(false);
                Administrador.setVisible(false);
                SombraAdmin.setVisible(false);
                SombraCouch.setVisible(false);
                SombraRecep.setVisible(false);
                SombraClie1.setVisible(false);
                Cliente.setLocation(530, 210);
                SombraClie.setLocation(460, 130);
                nivel = 5;
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnScrollDown = new javax.swing.JLabel();
        infofecha = new javax.swing.JLabel();
        Premium = new javax.swing.JLabel();
        Coach = new javax.swing.JLabel();
        Estandar = new javax.swing.JLabel();
        Gerente = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        SombraClie = new javax.swing.JLabel();
        Recepcionista = new javax.swing.JLabel();
        SombraRecep = new javax.swing.JLabel();
        SombraClie1 = new javax.swing.JLabel();
        PremiumSombra = new javax.swing.JLabel();
        Administrador = new javax.swing.JLabel();
        SombraEstandar = new javax.swing.JLabel();
        SombraAdmin = new javax.swing.JLabel();
        SombraCouch = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        DUI = new javax.swing.JFormattedTextField();
        Telefono = new javax.swing.JFormattedTextField();
        Fecha = new javax.swing.JFormattedTextField();
        Nombres = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        lblDatosPersonales = new javax.swing.JLabel();
        Mujer = new javax.swing.JLabel();
        MujerSombra = new javax.swing.JLabel();
        Hombre = new javax.swing.JLabel();
        HombreSombra = new javax.swing.JLabel();
        tarjetafinal = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        lblSombraPestana1 = new javax.swing.JLabel();
        btnScrollDown1 = new javax.swing.JLabel();
        lblSombraPestana = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnScrollDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Pestaña hacia abajo.png"))); // NOI18N
        btnScrollDown.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnScrollDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnScrollDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScrollDownMouseClicked(evt);
            }
        });
        add(btnScrollDown);
        btnScrollDown.setBounds(620, 886, 170, 90);

        infofecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        infofecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infofecha.setText("YYYY/mm/DD");
        add(infofecha);
        infofecha.setBounds(570, 1535, 92, 19);

        Premium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Membresía premium.png"))); // NOI18N
        Premium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PremiumMouseClicked(evt);
            }
        });
        add(Premium);
        Premium.setBounds(730, 540, 600, 300);

        Coach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta couch.png"))); // NOI18N
        Coach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoachMouseClicked(evt);
            }
        });
        add(Coach);
        Coach.setBounds(520, 160, 400, 150);

        Estandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Membresía estándar.png"))); // NOI18N
        Estandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstandarMouseClicked(evt);
            }
        });
        add(Estandar);
        Estandar.setBounds(90, 540, 600, 300);

        Gerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta gerente.png"))); // NOI18N
        Gerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GerenteMouseClicked(evt);
            }
        });
        add(Gerente);
        Gerente.setBounds(280, 350, 400, 150);

        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta cliente-h.png"))); // NOI18N
        add(Cliente);
        Cliente.setBounds(70, 160, 388, 146);

        SombraClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra cliente.png"))); // NOI18N
        add(SombraClie);
        SombraClie.setBounds(0, 80, 547, 301);

        Recepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta recepcionista.png"))); // NOI18N
        Recepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecepcionistaMouseClicked(evt);
            }
        });
        add(Recepcionista);
        Recepcionista.setBounds(970, 160, 400, 150);

        SombraRecep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra cliente.png"))); // NOI18N
        add(SombraRecep);
        SombraRecep.setBounds(920, 80, 547, 301);

        SombraClie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra cliente.png"))); // NOI18N
        add(SombraClie1);
        SombraClie1.setBounds(210, 270, 547, 301);

        PremiumSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra membresía premium.png"))); // NOI18N
        add(PremiumSombra);
        PremiumSombra.setBounds(670, 480, 730, 430);

        Administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta administrador.png"))); // NOI18N
        Administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministradorMouseClicked(evt);
            }
        });
        add(Administrador);
        Administrador.setBounds(740, 350, 400, 150);

        SombraEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra membresía estándar.png"))); // NOI18N
        add(SombraEstandar);
        SombraEstandar.setBounds(20, 480, 730, 430);

        SombraAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra admin.png"))); // NOI18N
        add(SombraAdmin);
        SombraAdmin.setBounds(670, 270, 547, 301);

        SombraCouch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra cliente.png"))); // NOI18N
        add(SombraCouch);
        SombraCouch.setBounds(450, 80, 547, 301);

        lblNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/1.png"))); // NOI18N
        add(lblNivel);
        lblNivel.setBounds(50, 0, 906, 154);

        lblDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/2.png"))); // NOI18N
        add(lblDatos);
        lblDatos.setBounds(50, 1000, 971, 154);

        DUI.setBorder(null);
        try {
            DUI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DUI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DUI.setToolTipText("");
        DUI.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        DUI.setOpaque(false);
        add(DUI);
        DUI.setBounds(880, 1382, 400, 50);

        Telefono.setBorder(null);
        try {
            Telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Telefono.setToolTipText("");
        Telefono.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Telefono.setOpaque(false);
        add(Telefono);
        Telefono.setBounds(940, 1480, 330, 50);

        Fecha.setBorder(null);
        try {
            Fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha.setToolTipText("");
        Fecha.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Fecha.setOpaque(false);
        add(Fecha);
        Fecha.setBounds(452, 1480, 320, 50);

        Nombres.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Nombres.setBorder(null);
        Nombres.setOpaque(false);
        Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombresKeyTyped(evt);
            }
        });
        add(Nombres);
        Nombres.setBounds(220, 1280, 430, 50);

        Email.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Email.setBorder(null);
        Email.setOpaque(false);
        add(Email);
        Email.setBounds(320, 1380, 420, 50);

        Direccion.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Direccion.setBorder(null);
        Direccion.setOpaque(false);
        add(Direccion);
        Direccion.setBounds(230, 1580, 1040, 50);

        Apellidos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Apellidos.setBorder(null);
        Apellidos.setOpaque(false);
        Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombresKeyTyped(evt);
            }
        });
        add(Apellidos);
        Apellidos.setBounds(850, 1280, 420, 50);

        lblDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Campos de datos personales.png"))); // NOI18N
        add(lblDatosPersonales);
        lblDatosPersonales.setBounds(80, 1270, 1210, 366);

        Mujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Mujer btn.png"))); // NOI18N
        Mujer.setToolTipText("");
        Mujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MujerMouseClicked(evt);
            }
        });
        add(Mujer);
        Mujer.setBounds(800, 1720, 200, 65);

        MujerSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra hombre.png"))); // NOI18N
        add(MujerSombra);
        MujerSombra.setBounds(760, 1680, 300, 154);

        Hombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Hombre.png"))); // NOI18N
        Hombre.setToolTipText("");
        Hombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HombreMouseClicked(evt);
            }
        });
        add(Hombre);
        Hombre.setBounds(470, 1720, 200, 65);

        HombreSombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Sombra hombre.png"))); // NOI18N
        add(HombreSombra);
        HombreSombra.setBounds(430, 1680, 300, 154);

        tarjetafinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Tarjeta final-Cliente.png"))); // NOI18N
        add(tarjetafinal);
        tarjetafinal.setBounds(140, 2020, 1208, 758);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar usuario/Botón agregar.png"))); // NOI18N
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        add(btnAgregar);
        btnAgregar.setBounds(980, 2770, 308, 140);

        lblSombraPestana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Sombra de pestaña.png"))); // NOI18N
        add(lblSombraPestana1);
        lblSombraPestana1.setBounds(520, 806, 370, 290);

        btnScrollDown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pestaña hacia abajo/Pestaña hacia abajo.png"))); // NOI18N
        btnScrollDown1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnScrollDown1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnScrollDown1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScrollDown1MouseClicked(evt);
            }
        });
        add(btnScrollDown1);
        btnScrollDown1.setBounds(640, 1865, 170, 90);

        lblSombraPestana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsuarioAssets/Sombra de pestaña.png"))); // NOI18N
        add(lblSombraPestana);
        lblSombraPestana.setBounds(540, 1760, 370, 290);

        lblError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setToolTipText("");
        add(lblError);
        lblError.setBounds(440, 2810, 540, 40);
    }// </editor-fold>//GEN-END:initComponents
    //Eventos
    private void btnScrollDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScrollDownMouseClicked
        UsuarioFormularioPrincipal.AddUserMover1();
    }//GEN-LAST:event_btnScrollDownMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        AgregarUsuario();
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnScrollDown1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScrollDown1MouseClicked
        UsuarioFormularioPrincipal.AddUserMover2();
    }//GEN-LAST:event_btnScrollDown1MouseClicked

    private void CoachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoachMouseClicked
        UsuarioAddUsuario.setNivel(4);
        UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
        UsuarioAddUsuario.Coach.setEnabled(false);
    }//GEN-LAST:event_CoachMouseClicked

    private void RecepcionistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecepcionistaMouseClicked
        UsuarioAddUsuario.setNivel(3);
        UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
        UsuarioAddUsuario.Recepcionista.setEnabled(false);
    }//GEN-LAST:event_RecepcionistaMouseClicked

    private void GerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GerenteMouseClicked
        UsuarioAddUsuario.setNivel(2);
        UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
        UsuarioAddUsuario.Gerente.setEnabled(false);
    }//GEN-LAST:event_GerenteMouseClicked

    private void AdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministradorMouseClicked
        UsuarioAddUsuario.setNivel(1);
        UsuarioFormularioPrincipal.Move(new UsuarioAddUsuario(), 1);
        UsuarioAddUsuario.Administrador.setEnabled(false);
        UsuarioAddUsuario.SombraAdmin.setEnabled(false);
    }//GEN-LAST:event_AdministradorMouseClicked

    private void EstandarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstandarMouseClicked
        membresia = 2;
        Estandar.setEnabled(false);
        Premium.setEnabled(true);
        PremiumSombra.setEnabled(true);
    }//GEN-LAST:event_EstandarMouseClicked

    private void PremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PremiumMouseClicked
        membresia = 1;
        Premium.setEnabled(false);
        PremiumSombra.setEnabled(false);
        Estandar.setEnabled(true);
    }//GEN-LAST:event_PremiumMouseClicked

    private void HombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HombreMouseClicked
        genero = 'M';
        Mujer.setEnabled(true);
        Hombre.setEnabled(false);
    }//GEN-LAST:event_HombreMouseClicked

    private void MujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MujerMouseClicked
        genero = 'F';
        Mujer.setEnabled(false);
        Hombre.setEnabled(true);
    }//GEN-LAST:event_MujerMouseClicked
    //Validación de texto
    private void NombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombresKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| c == KeyEvent.VK_SPACE)) {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_NombresKeyTyped
    //Método para agregar un cliente
    private void AgregarUsuario(){
        String [] dui = DUI.getText().split("-", 2);
        String [] fecha = Fecha.getText().split("-", 3);
        String [] telefono = Telefono.getText().split("-", 2);
        
        String STelefono = new StringBuilder().append(telefono[0]).append(telefono[1]).toString().trim();
        String SFecha = new StringBuilder().append(fecha[0]).append(fecha[1]).append(fecha[2]).toString().trim();
        String SDui = new StringBuilder().append(dui[0]).append(dui[1]).toString().trim();
        
        if (!Nombres.getText().trim().isEmpty() && !Apellidos.getText().trim().isEmpty() &&
            !Email.getText().trim().isEmpty() && !SDui.trim().isEmpty() &&
            !SFecha.trim().isEmpty() && !STelefono.trim().isEmpty() &&
            !Direccion.getText().trim().isEmpty() && 
            !(nivel == 0) && !(genero == 'G')){
            
            Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            
            Matcher mather = pattern.matcher(Email.getText());

            if (mather.find() == true) {
                String[] primer = Nombres.getText().split(" ", 0);
                String[] segun = Apellidos.getText().split(" ", 0);
                String uno = primer[0].toLowerCase();
                String dos = segun[0].toLowerCase();
                String usuario = new StringBuilder().append(uno).append(dos).toString();
                String[] fechan = Fecha.getText().split("-");
                Integer[] fechas = new Integer[fechan.length];
                int i = 0;
                
                for(String f: fechan){
                    fechas[i]=Integer.parseInt(f);
                    i++;
                }
                
                if ((fechas[0] <= 2001 && fechas[1] <= 12) &&
                    ((fechas[1] == 1 && fechas[2] <= 31) ||
                    (fechas[1] == 2 && fechas[2] <= 29) ||
                    (fechas[1] == 3 && fechas[2] <= 31) ||
                    (fechas[1] == 4 && fechas[2] <= 30) ||
                    (fechas[1] == 5 && fechas[2] <= 31) ||
                    (fechas[1] == 6 && fechas[2] <= 30) ||
                    (fechas[1] == 7 && fechas[2] <= 31) ||
                    (fechas[1] == 8 && fechas[2] <= 31) ||
                    (fechas[1] == 9 && fechas[2] <= 30) ||
                    (fechas[1] == 10 && fechas[2] <= 31) ||
                    (fechas[1] == 11 && fechas[2] <= 30) ||
                    (fechas[1] == 12 && fechas[2] <= 31))){
                    if (!ThirdLayer.BackEndUsuarioCliente.GetExistingDUI(DUI.getText())){
                        ThirdLayer.BackEndUsuarioCliente.setNombres(Nombres.getText());
                        ThirdLayer.BackEndUsuarioCliente.setApellidos(Apellidos.getText());
                        ThirdLayer.BackEndUsuarioCliente.setUsuario(usuario);
                        ThirdLayer.BackEndUsuarioCliente.setContrasena("FitL0gic");
                        ThirdLayer.BackEndUsuarioCliente.setEmail(Email.getText());
                        ThirdLayer.BackEndUsuarioCliente.setGenero(genero);
                        ThirdLayer.BackEndUsuarioCliente.setDui(DUI.getText());
                        ThirdLayer.BackEndUsuarioCliente.setNacimiento(Fecha.getText());
                        ThirdLayer.BackEndUsuarioCliente.setDireccion(Direccion.getText());
                        ThirdLayer.BackEndUsuarioCliente.setTelefono(Telefono.getText());
                        ThirdLayer.BackEndUsuarioCliente.setIdtipousuario(getNivel());
                        ThirdLayer.BackEndUsuarioCliente.setIdestado(1);
                        ThirdLayer.BackEndUsuarioCliente.setPrimerinicio(1);
                        ThirdLayer.BackEndUsuarioCliente.setIdmembresia(membresia);
                        if (ThirdLayer.BackEndUsuarioCliente.IngresarCliente()){
                            UsuarioFormularioPrincipal.Move(new UsuarioSeeUsuario(),3);
                            genero = 'G';
                            nivel = 0;
                        } else lblError.setText(
                        "<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                                + " por favor verifique los datos otra vez. Tiempo</p></html>"
                    );} else lblError.setText(
                    "<html><p style=\"style-align:center;\">El dui ingresado ya existe en nuestros registros, "
                            + "por favor verifíque si es correcto.</p></html>"
                );} else lblError.setText(
                "<html><p style=\"style-align:center;\">Uno de los campos tiene datos erroneos,"
                        + " por favor verifique los datos otra vez. Mail</p></html>"
            );} else lblError.setText(
                "<html><p style=\"style-align:center;\">Por favor rellene todos los campos para continuar. Vacio</p></html>"
        );} else lblError.setText(
            "<html><p style=\"style-align:center;\">Por favor rellene todos los campos para continuar. </p></html>"
    );}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Administrador;
    private javax.swing.JTextField Apellidos;
    public static javax.swing.JLabel Cliente;
    public static javax.swing.JLabel Coach;
    private javax.swing.JFormattedTextField DUI;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Estandar;
    private javax.swing.JFormattedTextField Fecha;
    public static javax.swing.JLabel Gerente;
    private javax.swing.JLabel Hombre;
    private javax.swing.JLabel HombreSombra;
    private javax.swing.JLabel Mujer;
    private javax.swing.JLabel MujerSombra;
    private javax.swing.JTextField Nombres;
    private javax.swing.JLabel Premium;
    private javax.swing.JLabel PremiumSombra;
    public static javax.swing.JLabel Recepcionista;
    private javax.swing.JLabel SombraAdmin;
    private javax.swing.JLabel SombraClie;
    private javax.swing.JLabel SombraClie1;
    private javax.swing.JLabel SombraCouch;
    private javax.swing.JLabel SombraEstandar;
    private javax.swing.JLabel SombraRecep;
    private javax.swing.JFormattedTextField Telefono;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnScrollDown;
    private javax.swing.JLabel btnScrollDown1;
    private javax.swing.JLabel infofecha;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDatosPersonales;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSombraPestana;
    private javax.swing.JLabel lblSombraPestana1;
    private javax.swing.JLabel tarjetafinal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nivel
     */
    public static int getNivel() {
        return nivel;
    }

    /**
     * @param aNivel the nivel to set
     */
    public static void setNivel(int aNivel) {
        nivel = aNivel;
    }
}
